import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file) => JSON.parse(fs.readFileSync(path.join(root, file), "utf8"));
const write = (file, value) => fs.writeFileSync(path.join(root, file), `${JSON.stringify(value, null, 2)}\n`);
const bi = (en, de) => ({ en, de });

// A deliberately small, source-led record for each new destination. Coordinates
// identify the named visitor area; they are never used as a substitute for
// current opening, parking, camping, or permit information.
const candidates = [
  ["isle-of-sark", "Isle of Sark", "GB", "United Kingdom", "europe", ["channel-islands", "europe"], "Europe/Guernsey", 86, ["island", "dark-sky-community", "coastal"], "Isle of Sark Channel Islands", ["sark", "Sark", 49.43, -2.36], [["sark-lighthouse", "Sark Lighthouse approach", 49.43, -2.36, 90, "coastal-viewpoint", "limited", 70], ["sark-windmill", "Sark Windmill lane", 49.43, -2.35, 70, "rural-lane", "limited", 64]], ["https://darksky.org/places/sark-dark-sky-community/", "https://sark.co.uk/plan-your-visit/", "https://sark.co.uk/getting-around/"], "island darkness and a short return", "Inselhimmel und kurzer Rückweg"],
  ["sierra-morena", "Sierra Morena", "ES", "Spain", "europe", ["andalusia", "europe"], "Europe/Madrid", 88, ["starlight-reserve", "mountains", "rural"], "Sierra Morena Spain stargazing", ["constantina", "Constantina", 37.87, -5.62], [["sierra-morena-constantina", "Constantina astronomy area", 37.88, -5.62, 560, "rural-viewpoint", "limited", 72], ["sierra-morena-almadén", "Almadén de la Plata approach", 37.87, -6.08, 460, "rural-viewpoint", "limited", 66]], ["https://www.juntadeandalucia.es/medioambiente/portal/areas-tematicas/espacios-naturales", "https://www.andalucia.org/en/stargazing", "https://www.turismosierramorena.com/"], "a rural Andalusian plan with no late crossing", "Ein ländlicher Andalusien-Plan ohne späte Querung"],
  ["monfrague", "Monfragüe", "ES", "Spain", "europe", ["extremadura", "europe"], "Europe/Madrid", 87, ["national-park", "dark-sky", "river"], "Monfrague National Park Spain", ["torrejón-el-rubio", "Torrejón el Rubio", 39.85, -5.98], [["monfrague-castillo", "Monfragüe castle viewpoint", 39.84, -6.06, 420, "park-viewpoint", "limited", 68], ["monfrague-salto-gitano", "Salto del Gitano area", 39.83, -6.03, 300, "river-viewpoint", "limited", 62]], ["https://www.miteco.gob.es/es/parques-nacionales-oapn/red-parques-nacionales/parques-nacionales/monfrague.html", "https://www.turismoextremadura.com/en/", "https://www.juntaex.es/temas/medio-ambiente/espacios-naturales"], "a park road that ends before the night becomes uncertain", "Eine Parkstraße, die endet, bevor die Nacht unsicher wird"],
  ["sierra-de-gredos", "Sierra de Gredos", "ES", "Spain", "europe", ["castile-and-leon", "europe"], "Europe/Madrid", 85, ["mountain", "starlight", "highland"], "Sierra de Gredos Spain astronomy", ["navarredonda-de-gredos", "Navarredonda de Gredos", 40.36, -5.13], [["garganta-de-los-infernós", "Gredos valley access", 40.25, -5.21, 1550, "mountain-valley", "limited", 64], ["guisando-gredos", "Guisando mountain area", 40.22, -5.14, 1150, "mountain-viewpoint", "limited", 62]], ["https://www.turismocastillayleon.com/en/nature", "https://www.jcyl.es/web/en/environment.html", "https://www.turismoavila.com/"], "a highland night built around one valley", "Eine Hochlandnacht rund um ein einziges Tal"],
  ["javalambre", "Javalambre", "ES", "Spain", "europe", ["aragon", "europe"], "Europe/Madrid", 89, ["mountain", "observatory", "rural"], "Javalambre Teruel Spain", ["arcos-de-las-salinas", "Arcos de las Salinas", 40.02, -1.00], [["javalambre-observatory-road", "Javalambre access area", 40.04, -1.01, 1950, "mountain-road", "limited", 58], ["arcos-salinas-viewpoint", "Arcos de las Salinas viewpoint", 40.02, -1.00, 1080, "village-viewpoint", "limited", 70]], ["https://www.cefca.es/", "https://www.turismodearagon.com/en/", "https://www.teruelversionamiga.es/"], "the public foothills rather than an observatory gate", "Das öffentliche Vorland statt eines Observatoriumstors"],
  ["aigues-tortes", "Aigüestortes", "ES", "Spain", "europe", ["catalonia", "europe"], "Europe/Madrid", 84, ["national-park", "mountain", "lake"], "Aiguestortes National Park Spain", ["espot", "Espot", 42.58, 1.09], [["aigues-estany-sant-maurici", "Estany de Sant Maurici route", 42.58, 1.02, 1910, "mountain-lake", "limited", 52], ["boi-valley", "Boí valley visitor area", 42.52, 0.83, 1260, "valley-viewpoint", "limited", 66]], ["https://parcsnaturals.gencat.cat/en/aiguestortes/", "https://www.miteco.gob.es/en/parques-nacionales-oapn/", "https://www.visitpirineus.com/en/"], "a park transfer and no invented night access", "Ein Parktransfer ohne erfundenen Nachtzugang"],
  ["vercors", "Vercors", "FR", "France", "europe", ["auvergne-rhone-alpes", "europe"], "Europe/Paris", 84, ["regional-park", "mountain", "forest"], "Vercors France stargazing", ["vassieux-en-vercors", "Vassieux-en-Vercors", 44.90, 5.37], [["col-de-la-machine", "Col de la Machine", 44.88, 5.27, 1015, "mountain-pass", "limited", 60], ["vassieux-plateau", "Vassieux plateau", 44.90, 5.37, 1050, "plateau-viewpoint", "limited", 68]], ["https://www.parc-du-vercors.fr/", "https://www.drome-tourism.com/en/", "https://www.auvergnerhonealpes-tourisme.com/en/"], "a plateau session that avoids exposed late driving", "Eine Plateausitzung ohne exponierte Spätfahrt"],
  ["attersee-traunsee", "Attersee-Traunsee", "AT", "Austria", "europe", ["upper-austria", "europe"], "Europe/Vienna", 80, ["dark-sky-park", "lake", "accessible"], "Attersee Traunsee dark sky Austria", ["unterach", "Unterach am Attersee", 47.80, 13.32], [["attersee-nussdorf", "Attersee lakeshore area", 47.90, 13.53, 480, "lakeshore", "limited", 58], ["traunsee-altaussee", "Traunsee rural shore", 47.87, 13.78, 430, "lakeshore", "limited", 54]], ["https://www.darksky-park.at/", "https://www.oberoesterreich.at/en/", "https://www.naturpark-attersee-traunsee.at/"], "a lakeside plan with fog as the deciding factor", "Ein Seeuferplan, bei dem Nebel entscheidet"],
  ["grossmugl", "Großmugl", "AT", "Austria", "europe", ["lower-austria", "europe"], "Europe/Vienna", 78, ["dark-sky-community", "rural", "accessible"], "Grossmugl Austria dark sky", ["grossmugl", "Großmugl", 48.49, 16.24], [["grossmugl-starwalk", "Großmugl star walk", 48.49, 16.24, 250, "rural-viewpoint", "limited", 74], ["leiserberge", "Leiser Berge area", 48.52, 16.35, 380, "hill-viewpoint", "limited", 62]], ["https://www.grossmugl.gv.at/", "https://www.niederoesterreich.at/en/", "https://www.darksky.at/"], "a close-to-Vienna dark-sky evening", "Ein Dark-Sky-Abend nahe Wien"],
  ["poloniny", "Poloniny", "SK", "Slovakia", "europe", ["presov", "europe"], "Europe/Bratislava", 86, ["dark-sky-park", "carpathians", "forest"], "Poloniny Dark Sky Park Slovakia", ["kolbasov", "Kolbasov", 49.02, 22.28], [["poloniny-runina", "Runina meadow", 49.07, 22.36, 560, "meadow", "limited", 66], ["poloniny-topola", "Topľa valley area", 49.12, 22.22, 440, "valley-viewpoint", "limited", 62]], ["https://www.slovakia.travel/en/places-to-go/regions/east-slovakia", "https://www.sopsr.sk/web/", "https://poloniny.sopsr.sk/"], "a Carpathian meadow with a strict daylight approach", "Eine Karpatenwiese mit strikter Tageslicht-Anfahrt"],
  ["izera", "Izera Dark-Sky Park", "PL", "Poland", "europe", ["lower-silesia", "europe"], "Europe/Warsaw", 85, ["dark-sky-park", "mountain", "forest"], "Izera Dark Sky Park Poland", ["izerska-hala", "Izera", 50.88, 15.34], [["izerska-hala", "Izera Meadow", 50.88, 15.34, 870, "mountain-meadow", "limited", 64], ["stóg-izerski", "Stóg Izerski area", 50.90, 15.31, 1105, "mountain-viewpoint", "limited", 56]], ["https://www.izerskipark.pl/", "https://www.gov.pl/web/gdos", "https://www.polska.travel/en"], "a Polish mountain meadow reached before the lifts stop", "Eine polnische Bergwiese, die vor Betriebsschluss erreicht wird"],
  ["tara-serbia", "Tara National Park", "RS", "Serbia", "europe", ["western-serbia", "europe"], "Europe/Belgrade", 82, ["national-park", "forest", "river"], "Tara National Park Serbia", ["bajina-basta", "Bajina Bašta", 43.97, 19.57], [["tara-mitrovac", "Mitrovac plateau", 43.92, 19.46, 1080, "plateau", "limited", 64], ["tara-banjica", "Banjica viewpoint", 43.91, 19.48, 950, "forest-viewpoint", "limited", 58]], ["https://www.nptara.rs/en/", "https://www.serbia.travel/en", "https://www.ekologija.gov.rs/"], "a forest reserve where the road matters more than the ranking", "Ein Waldreservat, in dem die Straße mehr zählt als der Rang"],
  ["kopaonik", "Kopaonik", "RS", "Serbia", "europe", ["central-serbia", "europe"], "Europe/Belgrade", 79, ["mountain", "national-park", "highland"], "Kopaonik National Park Serbia", ["kopaonik", "Kopaonik", 43.28, 20.81], [["kopaonik-pancic", "Pancic peak access", 43.28, 20.81, 2017, "mountain", "limited", 48], ["kopaonik-sunacana", "Sunčana dolina", 43.28, 20.82, 1650, "ski-area", "limited", 52]], ["https://npkopaonik.com/en/", "https://www.serbia.travel/en", "https://www.srbija.gov.rs/"], "a high resort plan outside lift and event hours", "Ein Hochgebirgsplan außerhalb von Lift- und Veranstaltungszeiten"],
  ["richtersveld", "Richtersveld", "ZA", "South Africa", "africa", ["northern-cape", "africa"], "Africa/Johannesburg", 90, ["national-park", "desert", "remote"], "Richtersveld National Park South Africa", ["sendelingsdrif", "Sendelingsdrif", -28.50, 17.07], [["richtersveld-potjiespram", "Potjiespram campsite", -28.38, 17.08, 410, "campground", "limited", 58], ["richtersveld-de-hoop", "De Hoop access area", -28.44, 17.02, 480, "desert-viewpoint", "limited", 54]], ["https://www.sanparks.org/parks/richtersveld", "https://www.sanparks.org/", "https://www.southafrica.net/"], "a remote desert night that starts with supplies", "Eine abgelegene Wüstennacht, die mit Vorräten beginnt"],
  ["mapungubwe", "Mapungubwe", "ZA", "South Africa", "africa", ["limpopo", "africa"], "Africa/Johannesburg", 84, ["national-park", "archaeology", "savanna"], "Mapungubwe National Park South Africa", ["mapungubwe", "Mapungubwe", -22.20, 29.39], [["mapungubwe-confluence", "Confluence viewpoint", -22.25, 29.40, 480, "park-viewpoint", "limited", 58], ["mapungubwe-camp", "Mapungubwe camp area", -22.24, 29.42, 520, "campground", "limited", 62]], ["https://www.sanparks.org/parks/mapungubwe", "https://www.sanparks.org/", "https://www.limpopo.gov.za/"], "a heritage landscape with no off-road shortcut", "Eine Kulturlandschaft ohne Abkürzung abseits der Straße"],
  ["makgadikgadi", "Makgadikgadi Pans", "BW", "Botswana", "africa", ["central-district", "africa"], "Africa/Gaborone", 88, ["salt-pan", "remote", "desert"], "Makgadikgadi Pans Botswana", ["nata", "Nata", -20.21, 25.19], [["nata-bird-sanctuary", "Nata sanctuary area", -20.23, 25.23, 930, "salt-pan", "limited", 52], ["makgadikgadi-kubu", "Kubu Island approach", -20.90, 24.60, 900, "salt-pan", "limited", 44]], ["https://www.botswanatourism.co.bw/", "https://www.gov.bw/", "https://www.botswanaparks.org/"], "a salt-pan night planned around water and road conditions", "Eine Salzpfannen-Nacht rund um Wasser und Straßenbedingungen"],
  ["tsumkwe", "Tsumkwe", "NA", "Namibia", "africa", ["otjozondjupa", "africa"], "Africa/Windhoek", 87, ["remote", "community", "savanna"], "Tsumkwe Namibia stargazing", ["tsumkwe", "Tsumkwe", -19.60, 20.50], [["tsumkwe-community", "Tsumkwe community area", -19.60, 20.50, 1110, "community-area", "limited", 48], ["naye-naye", "Naye-Naye access", -19.72, 20.74, 1090, "savanna-viewpoint", "limited", 42]], ["https://visitnamibia.com.na/", "https://www.meft.gov.na/", "https://www.nacso.org.na/"], "a community-led plan where local permission comes first", "Ein gemeinschaftsbasierter Plan, bei dem Zustimmung zuerst kommt"],
  ["rakiura", "Rakiura Stewart Island", "NZ", "New Zealand", "oceania", ["southland", "oceania"], "Pacific/Auckland", 89, ["dark-sky-sanctuary", "island", "coastal"], "Rakiura Stewart Island Dark Sky", ["oban-rakiura", "Oban", -46.90, 168.13], [["oban-bay", "Oban shoreline", -46.90, 168.13, 20, "coastal-viewpoint", "limited", 66], ["rakiura-horseshoe", "Horseshoe Bay", -46.88, 168.08, 15, "beach", "limited", 60]], ["https://rakiura.org.nz/", "https://www.doc.govt.nz/rakiura", "https://www.newzealand.com/int/stewart-island/"], "an island night limited by ferry and weather decisions", "Eine Inselnacht, begrenzt durch Fähre und Wetter"],
  ["kangaroo-island", "Kangaroo Island", "AU", "Australia", "oceania", ["south-australia", "oceania"], "Australia/Adelaide", 83, ["island", "coastal", "wildlife"], "Kangaroo Island South Australia stargazing", ["kingscote", "Kingscote", -35.66, 137.64], [["kangaroo-west-bay", "West Bay area", -35.99, 136.59, 20, "coastal-viewpoint", "limited", 58], ["kangaroo-flinders", "Flinders Chase area", -35.96, 136.68, 100, "national-park", "limited", 54]], ["https://www.parks.sa.gov.au/parks/kangaroo-island", "https://www.southaustralia.com/places-to-go/kangaroo-island", "https://www.environment.sa.gov.au/"], "a wildlife island night with a single settled base", "Eine Wildnisinsel-Nacht mit fester Basis"],
  ["mudgee", "Mudgee", "AU", "Australia", "oceania", ["new-south-wales", "oceania"], "Australia/Sydney", 80, ["rural", "vineyards", "accessible"], "Mudgee New South Wales stargazing", ["mudgee", "Mudgee", -32.59, 149.59], [["mudgee-observatory", "Mudgee region observatory area", -32.55, 149.56, 470, "rural-viewpoint", "limited", 62], ["gulgong", "Gulgong outskirts", -32.36, 149.53, 500, "rural-viewpoint", "limited", 58]], ["https://www.visitmudgeeregion.com.au/", "https://www.nationalparks.nsw.gov.au/", "https://www.environment.nsw.gov.au/"], "a dry inland evening without a long second drive", "Ein trockener Inlandabend ohne zweite lange Fahrt"],
  ["great-western-woodlands", "Great Western Woodlands", "AU", "Australia", "oceania", ["western-australia", "oceania"], "Australia/Perth", 90, ["remote", "woodland", "desert"], "Great Western Woodlands Western Australia", ["kalgoorlie", "Kalgoorlie", -30.75, 121.47], [["great-western-boorabbin", "Boorabbin woodland area", -31.18, 120.08, 430, "woodland", "limited", 44], ["great-western-holland", "Holland Track area", -31.45, 121.00, 390, "remote-road", "limited", 38]], ["https://www.dpaw.wa.gov.au/", "https://www.australiasgoldenoutback.com/", "https://www.wa.gov.au/service/environment"], "a supply-led outback night with no casual detour", "Eine vorratsorientierte Outback-Nacht ohne beiläufigen Umweg"],
  ["torrance-barrens", "Torrance Barrens", "CA", "Canada", "north-america", ["ontario", "north-america"], "America/Toronto", 82, ["dark-sky-reserve", "wetland", "accessible"], "Torrance Barrens Dark Sky Reserve Ontario", ["gravenhurst", "Gravenhurst", 44.92, -79.38], [["torrance-barrens-main", "Torrance Barrens conservation reserve", 44.91, -79.56, 260, "conservation-reserve", "limited", 64], ["torrance-barrens-boardwalk", "Torrance Barrens boardwalk", 44.90, -79.57, 260, "boardwalk", "limited", 56]], ["https://www.ontarioparks.com/park/torrancebarrens", "https://www.ontario.ca/page/crown-land-use-policy-atlas", "https://darksky.org/places/torrance-barrens-dark-sky-reserve/"], "a wetland reserve where the boardwalk is the boundary", "Ein Feuchtgebiet, dessen Steg die Grenze bildet"],
  ["fundy", "Fundy National Park", "CA", "Canada", "north-america", ["new-brunswick", "north-america"], "America/Moncton", 81, ["national-park", "coast", "forest"], "Fundy National Park stargazing Canada", ["alma-new-brunswick", "Alma", 45.60, -64.95], [["fundy-headquarters", "Fundy park headquarters", 45.59, -64.95, 35, "park-campus", "limited", 58], ["fundy-point-wolfe", "Point Wolfe area", 45.82, -65.00, 80, "coastal-viewpoint", "limited", 52]], ["https://parks.canada.ca/pn-np/nb/fundy", "https://parks.canada.ca/voyage-travel", "https://www2.gnb.ca/content/gnb/en/departments/erd.html"], "a tidal coast plan that does not chase clearings", "Ein Gezeitenküstenplan, der keiner Lichtung hinterherfährt"],
  ["manitoulin", "Manitoulin Island", "CA", "Canada", "north-america", ["ontario", "north-america"], "America/Toronto", 80, ["island", "lake", "rural"], "Manitoulin Island Ontario stargazing", ["little-current", "Little Current", 45.98, -81.92], [["manitoulin-meldrum", "Meldrum Bay area", 45.93, -83.12, 180, "lakeshore", "limited", 56], ["manitoulin-shearer", "Sheguiandah area", 45.78, -81.92, 190, "rural-viewpoint", "limited", 58]], ["https://www.ontarioparks.com/", "https://www.destinationontario.com/en-ca/regions/manitoulin-island", "https://www.manitoulin.ca/"], "an island itinerary tied to the ferry timetable", "Eine Inselroute, die am Fährplan hängt"],
  ["massacre-rim", "Massacre Rim", "US", "United States", "north-america", ["nevada", "north-america"], "America/Los_Angeles", 91, ["dark-sky-sanctuary", "desert", "remote"], "Massacre Rim Dark Sky Sanctuary Nevada", ["denio", "Denio", 41.73, -118.63], [["massacre-rim-viewpoint", "Massacre Rim access area", 41.58, -119.02, 1700, "desert-viewpoint", "limited", 40], ["denio-outskirts", "Denio outskirts", 41.73, -118.63, 1320, "rural-viewpoint", "limited", 46]], ["https://darksky.org/places/massacre-rim-dark-sky-sanctuary/", "https://www.blm.gov/visit/massacre-rim", "https://www.blm.gov/office/winnemucca-field-office"], "a remote Nevada plan that begins with fuel and water", "Ein abgelegener Nevada-Plan, der mit Kraftstoff und Wasser beginnt"],
  ["grand-canyon-parashant", "Grand Canyon-Parashant", "US", "United States", "north-america", ["arizona", "north-america"], "America/Phoenix", 90, ["national-monument", "desert", "remote"], "Grand Canyon Parashant National Monument stargazing", ["mesquite", "Mesquite", 36.81, -114.07], [["parashant-tuweep", "Tuweep overlook area", 36.28, -113.08, 1450, "rim-viewpoint", "limited", 34], ["parashant-mount-trumbull", "Mount Trumbull area", 36.42, -113.03, 1500, "desert-viewpoint", "limited", 40]], ["https://www.blm.gov/visit/grand-canyon-parashant", "https://www.blm.gov/visit", "https://www.nps.gov/grca/planyourvisit/"], "a high-clearance route with no improvised second site", "Eine Route für hohe Bodenfreiheit ohne improvisierten Zweitort"],
  ["oracle-state-park", "Oracle State Park", "US", "United States", "north-america", ["arizona", "north-america"], "America/Phoenix", 78, ["dark-sky-park", "desert", "accessible"], "Oracle State Park Arizona dark sky", ["oracle", "Oracle", 32.61, -110.77], [["oracle-state-park", "Oracle State Park Kannally Ranch", 32.61, -110.77, 1370, "state-park", "limited", 62], ["oracle-charouleau", "Charouleau Gap area", 32.62, -110.82, 1300, "desert-viewpoint", "limited", 52]], ["https://azstateparks.com/oracle", "https://azstateparks.com/", "https://darksky.org/places/oracle-state-park-dark-sky-park/"], "an accessible Arizona park with a clear closing-time check", "Ein zugänglicher Arizona-Park mit klarer Schließzeitprüfung"],
  ["enchanted-rock", "Enchanted Rock", "US", "United States", "north-america", ["texas", "north-america"], "America/Chicago", 77, ["state-park", "granite", "hill-country"], "Enchanted Rock State Natural Area stargazing", ["fredericksburg", "Fredericksburg", 30.28, -98.87], [["enchanted-rock-summit", "Enchanted Rock summit area", 30.51, -98.82, 556, "granite-dome", "limited", 48], ["enchanted-rock-camp", "Enchanted Rock campground", 30.50, -98.82, 430, "campground", "limited", 58]], ["https://tpwd.texas.gov/state-parks/enchanted-rock", "https://tpwd.texas.gov/", "https://darksky.org/places/enchanted-rock-state-natural-area/"], "a granite park where the summit is not the default", "Ein Granitpark, in dem der Gipfel nicht der Standard ist"],
  ["staunton-river", "Staunton River State Park", "US", "United States", "north-america", ["virginia", "north-america"], "America/New_York", 79, ["dark-sky-park", "river", "campground"], "Staunton River State Park Virginia astronomy", ["scottsburg", "Scottsburg", 36.78, -78.79], [["staunton-river-park", "Staunton River observing field", 36.78, -78.79, 120, "state-park", "limited", 66], ["staunton-river-camp", "Staunton River campground", 36.79, -78.80, 115, "campground", "limited", 62]], ["https://www.dcr.virginia.gov/state-parks/staunton-river", "https://www.dcr.virginia.gov/", "https://darksky.org/places/staunton-river-state-park/"], "a river park night that stays within the campground loop", "Eine Flussparknacht innerhalb der Campingrunde"],
  ["kissimmee-prairie", "Kissimmee Prairie", "US", "United States", "north-america", ["florida", "north-america"], "America/New_York", 76, ["dark-sky-park", "prairie", "wetland"], "Kissimmee Prairie Preserve State Park stargazing", ["okeechobee", "Okeechobee", 27.24, -80.83], [["kissimmee-prairie-north", "Kissimmee Prairie north entrance", 27.46, -81.02, 20, "prairie", "limited", 54], ["kissimmee-prairie-camp", "Kissimmee Prairie campground", 27.43, -81.01, 18, "campground", "limited", 58]], ["https://floridastateparks.org/parks-and-trails/kissimmee-prairie-preserve-state-park", "https://floridastateparks.org/", "https://darksky.org/places/kissimmee-prairie-preserve-state-park/"], "a flat prairie where weather and insects set the pace", "Eine flache Prärie, in der Wetter und Insekten das Tempo setzen"],
  ["big-cypress", "Big Cypress", "US", "United States", "north-america", ["florida", "north-america"], "America/New_York", 74, ["dark-sky-park", "wetland", "wildlife"], "Big Cypress National Preserve stargazing", ["ochopee", "Ochopee", 25.85, -81.39], [["big-cypress-wagonwheel", "Wagonwheel Road area", 25.89, -81.35, 3, "wetland-road", "limited", 46], ["big-cypress-camp", "Midway campground", 25.76, -81.08, 4, "campground", "limited", 52]], ["https://www.nps.gov/bicy/index.htm", "https://www.nps.gov/bicy/planyourvisit/conditions.htm", "https://darksky.org/places/big-cypress-national-preserve/"], "a humid preserve where wildlife rules outweigh convenience", "Ein feuchtes Schutzgebiet, in dem Wildtierregeln Vorrang haben"],
  ["lassen-volcanic", "Lassen Volcanic", "US", "United States", "north-america", ["california", "north-america"], "America/Los_Angeles", 84, ["national-park", "volcanic", "mountain"], "Lassen Volcanic National Park stargazing", ["mineral", "Mineral", 40.35, -121.61], [["lassen-manazanita", "Manzanita Lake area", 40.53, -121.58, 1780, "lake-viewpoint", "limited", 62], ["lassen-summit", "Lassen summit road area", 40.49, -121.51, 2600, "mountain-road", "limited", 38]], ["https://www.nps.gov/lavo/index.htm", "https://www.nps.gov/lavo/planyourvisit/conditions.htm", "https://darksky.org/places/lassen-volcanic-national-park/"], "a lake-level plan that respects the snow line", "Ein Plan auf Seehöhe, der die Schneegrenze respektiert"],
  ["dinosaur-national-monument", "Dinosaur National Monument", "US", "United States", "north-america", ["utah", "colorado", "north-america"], "America/Denver", 83, ["national-monument", "desert", "river"], "Dinosaur National Monument stargazing", ["vernal", "Vernal", 40.46, -109.54], [["dinosaur-jensen", "Jensen visitor area", 40.37, -109.35, 1760, "river-viewpoint", "limited", 58], ["dinosaur-harpers", "Harpers Corner road area", 40.48, -109.16, 1950, "rim-viewpoint", "limited", 48]], ["https://www.nps.gov/dino/index.htm", "https://www.nps.gov/dino/planyourvisit/conditions.htm", "https://darksky.org/places/dinosaur-national-monument/"], "a canyon road that needs daylight reconnaissance", "Eine Canyonstraße, die bei Tageslicht erkundet werden muss"],
  ["medicine-rocks", "Medicine Rocks", "US", "United States", "north-america", ["montana", "north-america"], "America/Denver", 82, ["state-park", "prairie", "dark-sky"], "Medicine Rocks State Park Montana stargazing", ["baker-montana", "Baker", 46.37, -104.77], [["medicine-rocks-park", "Medicine Rocks State Park", 46.06, -104.50, 1000, "prairie-rock", "limited", 54], ["medicine-rocks-camp", "Medicine Rocks campground", 46.06, -104.50, 1000, "campground", "limited", 58]], ["https://stateparks.mt.gov/medicine-rocks/", "https://stateparks.mt.gov/", "https://darksky.org/places/medicine-rocks-state-park/"], "a prairie stop where wind changes the comfort calculation", "Ein Präriehalt, an dem Wind den Komfort bestimmt"],
  ["newport-wisconsin", "Newport State Park", "US", "United States", "north-america", ["wisconsin", "north-america"], "America/Chicago", 78, ["dark-sky-park", "lake", "forest"], "Newport State Park Wisconsin stargazing", ["ellison-bay", "Ellison Bay", 45.25, -87.07], [["newport-porte-des-morts", "Newport shoreline", 45.25, -86.96, 185, "lakeshore", "limited", 62], ["newport-campground", "Newport campground", 45.25, -86.97, 185, "campground", "limited", 58]], ["https://dnr.wisconsin.gov/topic/parks/newport", "https://dnr.wisconsin.gov/", "https://darksky.org/places/newport-state-park/"], "a Lake Michigan shore plan with no beach-hopping", "Ein Lake-Michigan-Uferplan ohne Strandhopping"],
  ["boundary-waters", "Boundary Waters", "US", "United States", "north-america", ["minnesota", "north-america"], "America/Chicago", 86, ["wilderness", "lake", "canoe"], "Boundary Waters Canoe Area Wilderness stargazing", ["ely", "Ely", 47.90, -91.87], [["boundary-waters-moose-lake", "Moose Lake entry area", 48.01, -91.50, 430, "wilderness-entry", "limited", 42], ["boundary-waters-seagull", "Seagull Lake entry", 48.12, -90.99, 440, "wilderness-entry", "limited", 38]], ["https://www.fs.usda.gov/recarea/superior/recarea/?recid=36910", "https://www.fs.usda.gov/superior", "https://www.fs.usda.gov/visit/know-before-you-go"], "a permit-led wilderness night with no roadside fallback", "Eine erlaubnisgebundene Wildnisnacht ohne Straßenfallback"],
  ["sturt-stony-desert", "Sturt Stony Desert", "AU", "Australia", "oceania", ["south-australia", "oceania"], "Australia/Adelaide", 88, ["desert", "remote", "outback"], "Sturt Stony Desert South Australia", ["innamincka", "Innamincka", -27.75, 140.73], [["sturt-stony-innamincka", "Innamincka Regional Reserve", -27.75, 140.73, 25, "desert", "limited", 42], ["sturt-stony-cooper", "Cooper Creek area", -27.55, 140.75, 20, "river-desert", "limited", 40]], ["https://www.parks.sa.gov.au/parks/innamincka-regional-reserve", "https://www.parks.sa.gov.au/", "https://www.environment.sa.gov.au/"], "a desert plan where water and tyre checks come first", "Ein Wüstenplan, bei dem Wasser und Reifen zuerst geprüft werden"],
  ["alula", "AlUla", "SA", "Saudi Arabia", "asia", ["al-madinah", "asia"], "Asia/Riyadh", 84, ["desert", "heritage", "guided"], "AlUla Saudi Arabia stargazing", ["alula", "AlUla", 26.61, 37.92], [["alula-harrat", "Harrat viewpoint", 26.65, 37.88, 900, "desert-viewpoint", "limited", 52], ["alula-hegra", "Hegra visitor area", 26.80, 37.96, 700, "heritage-site", "limited", 42]], ["https://www.experiencealula.com/en", "https://www.rcu.gov.sa/en", "https://darksky.org/"], "a heritage desert evening that follows the operator plan", "Ein Kulturerbe-Abend in der Wüste nach Betreiberplan"],
  ["jebel-akhdar", "Jebel Akhdar", "OM", "Oman", "asia", ["ad-dakhiliyah", "asia"], "Asia/Muscat", 86, ["mountain", "desert", "remote"], "Jebel Akhdar Oman stargazing", ["nizwa", "Nizwa", 22.93, 57.53], [["jebel-akhdar-diana", "Diana's Point", 23.07, 57.66, 2000, "mountain-viewpoint", "limited", 46], ["jebel-akhdar-saiq", "Saiq plateau", 23.08, 57.65, 1900, "plateau", "limited", 52]], ["https://experienceoman.om/", "https://www.omantourism.gov.om/", "https://www.rop.gov.om/"], "a mountain night that needs a four-wheel-drive decision", "Eine Bergnacht, die eine Allradentscheidung verlangt"],
  ["rann-of-kutch", "Rann of Kutch", "IN", "India", "asia", ["gujarat", "asia"], "Asia/Kolkata", 84, ["salt-desert", "seasonal", "remote"], "Rann of Kutch Gujarat India stargazing", ["bhuj", "Bhuj", 23.24, 69.67], [["rann-dhordo", "Dhordo white desert", 23.84, 69.57, 15, "salt-desert", "limited", 48], ["rann-kalo-dungar", "Kalo Dungar area", 23.82, 69.58, 460, "hill-viewpoint", "limited", 44]], ["https://www.gujarattourism.com/", "https://gujaratindia.gov.in/", "https://www.incredibleindia.gov.in/en/gujarat"], "a seasonal salt desert where permits set the route", "Eine saisonale Salzwüste, deren Route Genehmigungen bestimmen"],
  ["achi-village", "Achi Village", "JP", "Japan", "asia", ["nagano", "asia"], "Asia/Tokyo", 82, ["dark-sky-community", "mountain", "village"], "Achi Village Japan stargazing", ["achi", "Achi", 35.44, 137.72], [["achi-heavens-sonohara", "Sonohara night-tour area", 35.43, 137.70, 1400, "mountain-resort", "limited", 58], ["achi-village", "Achi village outskirts", 35.45, 137.71, 600, "village-viewpoint", "limited", 62]], ["https://sva.jp/", "https://www.vill.achi.lg.jp/", "https://www.go-nagano.net/en/"], "a booked ropeway experience rather than an improvised summit", "Ein gebuchtes Seilbahnerlebnis statt eines improvisierten Gipfels"],
  ["sani-pass", "Sani Pass", "LS", "Lesotho", "africa", ["mokhotlong", "africa"], "Africa/Maseru", 87, ["mountain", "highland", "remote"], "Sani Pass Lesotho stargazing", ["mokhotlong", "Mokhotlong", -29.29, 29.07], [["sani-pass-border", "Sani Pass upper road", -29.59, 29.29, 2874, "mountain-pass", "limited", 34], ["sani-top", "Sani Top area", -29.59, 29.29, 2874, "mountain-viewpoint", "limited", 30]], ["https://www.lesotho-tourism.com/", "https://www.gov.ls/", "https://www.sanparks.org/parks/maloti-drakensberg"], "a border road whose daylight rule is non-negotiable", "Eine Grenzstraße mit unverhandelbarer Tageslichtregel"],
  ["drakensberg", "Maloti-Drakensberg", "ZA", "South Africa", "africa", ["kwazulu-natal", "africa"], "Africa/Johannesburg", 85, ["mountain", "world-heritage", "highland"], "Maloti Drakensberg South Africa stargazing", ["underberg", "Underberg", -29.79, 29.51], [["drakensberg-giants-castle", "Giants Castle area", -29.40, 29.46, 1700, "mountain-valley", "limited", 48], ["drakensberg-camp", "Didima camp area", -28.68, 28.99, 1500, "campground", "limited", 56]], ["https://www.sanparks.org/parks/maloti-drakensberg", "https://www.kznwildlife.com/", "https://whc.unesco.org/en/list/985/"], "a highland camp plan with weather as the final veto", "Ein Hochland-Campingplan mit Wetter als letztem Veto"],
  ["northern-damaraland", "Northern Damaraland", "NA", "Namibia", "africa", ["kunene", "africa"], "Africa/Windhoek", 89, ["desert", "remote", "geology"], "Northern Damaraland Namibia stargazing", ["sesfontein", "Sesfontein", -19.13, 13.62], [["damaraland-twyfelfontein", "Twyfelfontein area", -20.59, 14.37, 700, "desert-heritage", "limited", 44], ["damaraland-palmwag", "Palmwag concession", -19.88, 13.95, 900, "desert-camp", "limited", 42]], ["https://visitnamibia.com.na/", "https://www.meft.gov.na/", "https://www.nacso.org.na/"], "a concession night that follows camp rules, not the map", "Eine Konzessionsnacht nach Campregeln und nicht nach der Karte"],
  ["coral-pink-sand-dunes", "Coral Pink Sand Dunes", "US", "United States", "north-america", ["utah", "north-america"], "America/Denver", 76, ["state-park", "desert", "accessible"], "Coral Pink Sand Dunes Utah stargazing", ["kanab", "Kanab", 37.04, -112.53], [["coral-pink-park", "Coral Pink Sand Dunes State Park", 37.04, -112.71, 1820, "sand-dunes", "limited", 56], ["coral-pink-camp", "Coral Pink campground", 37.04, -112.71, 1820, "campground", "limited", 58]], ["https://stateparks.utah.gov/parks/coral-pink/", "https://stateparks.utah.gov/", "https://darksky.org/places/coral-pink-sand-dunes-state-park/"], "a dune park where walking distance changes after sunset", "Ein Dünenpark, in dem sich Gehstrecken nach Sonnenuntergang ändern"],
  ["cedar-breaks", "Cedar Breaks", "US", "United States", "north-america", ["utah", "north-america"], "America/Denver", 81, ["national-monument", "highland", "snow"], "Cedar Breaks National Monument stargazing", ["cedar-city", "Cedar City", 37.68, -113.06], [["cedar-breaks-sunset", "Sunset View Overlook", 37.63, -112.84, 3150, "rim-viewpoint", "limited", 42], ["cedar-breaks-camp", "Point Supreme area", 37.63, -112.84, 3150, "rim-viewpoint", "limited", 38]], ["https://www.nps.gov/cebr/index.htm", "https://www.nps.gov/cebr/planyourvisit/conditions.htm", "https://darksky.org/places/cedar-breaks-national-monument/"], "a high rim that may close long before dark", "Ein hoher Rand, der lange vor Dunkelheit schließen kann"],
  ["puna-argentina", "Puna de Atacama", "AR", "Argentina", "south-america", ["jujuy", "south-america"], "America/Argentina/Jujuy", 90, ["high-altitude", "desert", "remote"], "Puna de Atacama Argentina stargazing", ["purmamarca", "Purmamarca", -23.75, -65.50], [["puna-salinas", "Salinas Grandes access", -23.65, -65.00, 3450, "salt-flat", "limited", 42], ["puna-humahuaca", "Quebrada highland area", -23.20, -65.35, 3000, "highland", "limited", 46]], ["https://www.argentina.gob.ar/ambiente", "https://www.jujuy.gob.ar/", "https://www.argentina.travel/en"], "a thin-air night where acclimatisation is part of the route", "Eine Nacht in dünner Luft, bei der Akklimatisation dazugehört"],
  ["isla-navarino", "Isla Navarino", "CL", "Chile", "south-america", ["magallanes", "south-america"], "America/Punta_Arenas", 86, ["island", "subantarctic", "remote"], "Isla Navarino Chile stargazing", ["puerto-williams", "Puerto Williams", -54.93, -67.61], [["navarino-puerto-williams", "Puerto Williams waterfront", -54.93, -67.61, 10, "waterfront", "limited", 58], ["navarino-dientes", "Dientes de Navarino approach", -54.98, -67.55, 250, "mountain-approach", "limited", 40]], ["https://www.conaf.cl/parques-nacionales/", "https://www.sernatur.cl/", "https://www.gob.cl/en/"], "a subantarctic night that stays close to the settlement", "Eine subantarktische Nacht nahe der Siedlung"],
  ["uyuni", "Uyuni", "BO", "Bolivia", "south-america", ["potosi", "south-america"], "America/La_Paz", 88, ["salt-flat", "high-altitude", "remote"], "Uyuni Bolivia stargazing", ["uyuni", "Uyuni", -20.46, -66.83], [["uyuni-salt-flat", "Salar de Uyuni access", -20.13, -67.49, 3650, "salt-flat", "limited", 38], ["uyuni-tahua", "Tahúa lakeshore", -20.08, -66.50, 3700, "highland-lake", "limited", 34]], ["https://www.turismo.produccion.gob.bo/", "https://www.bolivia.gob.bo/", "https://www.sernap.gob.bo/"], "a salt-flat plan that requires a local driver and route", "Ein Salzpfannenplan mit lokalem Fahrer und fester Route"],
  ["kidepo-valley", "Kidepo Valley", "UG", "Uganda", "africa", ["karamoja", "africa"], "Africa/Kampala", 84, ["national-park", "savanna", "remote"], "Kidepo Valley National Park Uganda stargazing", ["kitgum", "Kitgum", 3.30, 32.88], [["kidepo-narus", "Narus valley camp", 3.93, 33.88, 950, "savanna-camp", "limited", 42], ["kidepo-kanangorok", "Kanangorok hot springs area", 4.14, 33.86, 1200, "savanna-viewpoint", "limited", 34]], ["https://ugandawildlife.org/national-parks/kidepo-valley-national-park/", "https://ugandawildlife.org/", "https://www.tourism.go.ug/"], "a wildlife reserve night that stays with the camp team", "Eine Wildnisnacht, die beim Campteam bleibt"],
];

if (candidates.length !== 50) throw new Error(`Expected 50 new destinations, found ${candidates.length}`);

const sourceRecords = (item) => item[12].map((url, index) => ({
  id: `${item[0]}-source-${index + 1}`,
  title: `${item[1]} source ${index + 1}`,
  url,
  publisher: new URL(url).hostname.replace(/^www\./, ""),
  checkedAt: "2026-09-16",
  authority: index === 0 ? "official-destination" : "public-agency",
}));

const makeGuide = (item, index) => {
  const [id, name, countryCode, countryName, continent, regions, timezone, priority, tags, affiliateQuery, stay, sites, urls, angleEn, angleDe] = item;
  const angleEnglish = angleEn.charAt(0).toUpperCase() + angleEn.slice(1);
  const angleGerman = angleDe.charAt(0).toUpperCase() + angleDe.slice(1);
  const primary = sites[0][1];
  const secondary = sites[1][1];
  const base = stay[1];
  const sourceIds = urls.map((_, n) => `${id}-source-${n + 1}`);
  const sections = [
    { id: `${id}-where`, heading: bi(`Where this ${name} plan really happens`, `Wo dieser ${name}-Plan wirklich stattfindet`), paragraphs: { en: [`${name} is best treated as a defined travel area rather than a promise attached to every dark patch on a map. ${primary} is the practical first choice because it gives the evening a named footprint, an approach that can be checked in daylight and a clear point at which to stop unloading. ${angleEnglish} Visitors should read the current authority notice before travel because a designation, a photograph or a familiar map label does not grant tonight's access.`, `${secondary} remains useful as a separate option, not as an automatic second stop. Its surface, road, gate, weather exposure and local rules can differ from ${primary}. Keeping the two decisions apart makes the route easier to cancel safely when the first check fails and avoids turning a good climatological ranking into an unsafe itinerary.`], de: [`${name} sollte als klar umrissene Reisezone verstanden werden und nicht als Versprechen für jeden dunklen Kartenfleck. ${primary} ist die praktische erste Wahl, weil der Abend dort eine benannte Fläche, eine bei Tageslicht prüfbare Zufahrt und einen klaren Punkt zum Ausladen erhält. ${angleGerman} Prüfe die aktuelle Verwaltungsinformation vor der Fahrt, denn Auszeichnung, Foto oder Kartenname gewähren keinen heutigen Zugang.`, `${secondary} bleibt eine getrennte Möglichkeit und kein automatischer zweiter Halt. Fläche, Straße, Tor, Wetter und lokale Regeln können sich von ${primary} unterscheiden. Die Trennung macht eine sichere Absage leichter, wenn die erste Prüfung scheitert, und verhindert, dass eine gute Klimareihung zu einer riskanten Route wird.`] }, sourceIds },
    { id: `${id}-conditions`, heading: bi(`Conditions that decide a ${name} night`, `Bedingungen, die eine ${name}-Nacht entscheiden`), paragraphs: { en: [`The useful forecast is the one for the actual elevation and exposed terrain, not for ${base} alone. Clouds, wind, humidity, smoke, snow, insects or heat can change the experience within a short distance. Treat the monthly score as a comparison of historical inputs and use the live forecast and current notices as the go or no-go decision.`, `Access has an equally practical veto. Check opening hours, permits, reservations, road restrictions, seasonal services and the return before leaving ${base}. Save the relevant pages offline. If the authority is silent about the intended hour, the responsible interpretation is uncertainty, not permission. A short session at a confirmed place is more useful than a longer drive built on an assumption.`], de: [`Die brauchbare Prognose gilt für die tatsächliche Höhe und das exponierte Gelände und nicht nur für ${base}. Wolken, Wind, Feuchte, Rauch, Schnee, Insekten oder Hitze können das Erlebnis auf kurzer Strecke verändern. Der Monatswert vergleicht historische Eingaben. Live-Wetter und aktuelle Hinweise entscheiden über Start oder Verschiebung.`, `Auch der Zugang hat ein praktisches Veto. Prüfe Öffnung, Genehmigungen, Reservierungen, saisonale Dienste, Straßenregeln und Rückweg vor der Abfahrt aus ${base}. Speichere die Seiten offline. Schweigt die Verwaltung zur geplanten Uhrzeit, bedeutet das Unsicherheit und keine Erlaubnis. Eine kurze Sitzung an bestätigtem Ort ist besser als eine längere Fahrt auf Annahmen.`] }, sourceIds },
    { id: `${id}-equipment`, heading: bi(`A workable kit for ${name}`, `Eine brauchbare Ausrüstung für ${name}`), paragraphs: { en: [`Keep the equipment proportionate to the access model at ${primary}. A red light should be dim and pointed down, a phone should be prepared before the dark interval and every loose item should have a place in the vehicle. In remote, high, wet or wildlife-sensitive settings, warmth, water, navigation and a charged backup matter before optical ambition.`, `At ${primary}, the surface is part of the equipment decision. A tripod, telescope or camera is only an advantage when it can be carried and packed without widening the footprint or blocking other users. Observe first with unaided eyes, then add the instrument that fits the confirmed space at ${name}. Leave enough attention for signs, weather changes and the return.`], de: [`Halte die Ausrüstung an das Zugangsmodell von ${primary} angepasst. Rotlicht bleibt gedimmt und zeigt nach unten. Bereite das Telefon vor der Dunkelheit vor und gib jedem Kleinteil einen festen Platz im Fahrzeug. In abgelegener, hoher, nasser oder wildsensibler Umgebung zählen Wärme, Wasser, Navigation und Reserveenergie vor optischem Ehrgeiz.`, `An ${primary} gehört die Fläche zur Ausrüstungsentscheidung. Stativ, Teleskop oder Kamera helfen nur, wenn sie getragen und gepackt werden können, ohne die Fläche zu vergrößern oder andere Nutzer zu behindern. Beobachte zuerst mit bloßem Auge und ergänze erst dann das Gerät, das zur bestätigten Fläche in ${name} passt. Aufmerksamkeit für Schilder, Wetter und Rückweg bleibt nötig.`] }, sourceIds },
    { id: `${id}-route`, heading: bi(`The one-evening route from ${base}`, `Die Ein-Abend-Route ab ${base}`), paragraphs: { en: [`Leave ${base} with the access page, weather check and return route already available offline. Reach ${primary} before sunset, read the signs and surface while there is light, and place the vehicle only where the current rule permits. Do not add ${secondary} because the first stop feels imperfect; a second site belongs to another confirmed evening.`, `After twilight, let adaptation settle before judging the sky. Keep light, voices and movement inside the established footprint, and record any changed detail for a later revision. End before fatigue, cold or wind turns a small uncertainty into a driving problem. The successful outcome is a calm return to ${base}, not the maximum number of map pins.`], de: [`Verlasse ${base} erst, wenn Zugangsseite, Wetterprüfung und Rückweg offline bereitstehen. Erreiche ${primary} vor Sonnenuntergang, lies Schilder und Untergrund bei Licht und stelle das Fahrzeug nur nach aktueller Regel ab. Ergänze ${secondary} nicht, nur weil der erste Ort unvollkommen wirkt; der zweite Ort gehört in einen anderen bestätigten Abend.`, `Lass die Augen nach der Dämmerung anpassen, bevor du den Himmel beurteilst. Halte Licht, Stimmen und Bewegung innerhalb der bestehenden Fläche und notiere jede Änderung für eine spätere Überarbeitung. Beende den Abend, bevor Müdigkeit, Kälte oder Wind eine kleine Unsicherheit zum Fahrproblem machen. Ein ruhiger Rückweg nach ${base} zählt mehr als viele Kartenmarken.`] }, sourceIds },
  ];
  if (index % 2) sections.reverse();
  return {
    version: 1, destinationId: id, slug: id,
    seoTitle: bi(`${name} stargazing guide and observing sites`, `Stargazing-Guide ${name} und Beobachtungsorte`),
    seoDescription: bi(`Plan a source-led stargazing night in ${name} with ${primary}, access checks and a practical return route.`, `Plane eine quellenbasierte Beobachtungsnacht in ${name} mit ${primary}, Zugangsprüfung und sicherem Rückweg.`),
    standfirst: bi(`${name} rewards a specific plan. ${angleEnglish} This guide separates the named observing places from the live decisions that remain with visitors and the managing authority. It is written for a real evening, including the point at which postponing is the correct decision, and keeps the practical return visible throughout the planning.`, `${name} belohnt einen konkreten Plan. ${angleGerman} Dieser Guide trennt benannte Beobachtungsorte von den aktuellen Entscheidungen der Gäste und der zuständigen Verwaltung. Er beschreibt einen echten Abend einschließlich des Punkts, an dem Verschieben die richtige Entscheidung ist, und hält den praktischen Rückweg während der Planung sichtbar.`),
    editorialAngle: bi(`${angleEnglish} The route keeps ${primary} as the decision point, treats ${secondary} as a separate option and makes the return part of a successful night.`, `${angleGerman} Die Route macht ${primary} zum Entscheidungspunkt, behandelt ${secondary} als getrennte Option und versteht die Rückkehr als Teil einer gelungenen Nacht.`),
    sections,
    tour: { title: bi(`${name}: ${angleEnglish}`, `${name}: ${angleGerman}`), summary: bi(`Use ${primary} as the fixed evening stop from ${base}. ${angleEnglish} Current access, weather and return checks still decide whether the plan runs. The route deliberately avoids a second late drive and treats a calm return as part of the observing experience.`, `Nutze ${primary} als festen Abendhalt ab ${base}. ${angleGerman} Aktuelle Zugangs-, Wetter- und Rückwegprüfungen entscheiden dennoch über die Durchführung. Die Route vermeidet bewusst eine zweite späte Fahrt und versteht die ruhige Rückkehr als Teil des Beobachtungserlebnisses.`), duration: bi("One evening with daylight arrival and a direct return", "Ein Abend mit Ankunft bei Tageslicht und direkter Rückkehr"), suitability: bi(`For independent visitors who can verify current ${name} access, keep equipment within the confirmed footprint and return without improvisation.`, `Für unabhängige Gäste, die den aktuellen Zugang in ${name} prüfen, die Ausrüstung innerhalb der bestätigten Fläche halten und ohne Improvisation zurückkehren können.`), sourceIds, steps: [
      { id: `${id}-check`, timeHint: bi(`Before leaving ${base}`, `Vor der Abfahrt aus ${base}`), title: bi("Confirm access, weather and return", "Zugang, Wetter und Rückweg bestätigen"), body: bi(`Open the current authority pages for ${name}, check the exact elevation and save directions offline. A dark-sky label does not confirm today's gate, road or reservation. Also note who to contact when an on-site notice changes the plan.`, `Öffne die aktuellen Verwaltungsseiten für ${name}, prüfe die genaue Höhe und speichere die Navigation offline. Ein Dark-Sky-Label bestätigt weder heutiges Tor, Straße noch Reservierung. Notiere außerdem, wen du bei einer Änderung vor Ort kontaktieren kannst.`), sourceIds },
      { id: `${id}-arrive`, timeHint: bi("Before sunset", "Vor Sonnenuntergang"), title: bi(`Settle at ${primary}`, `An ${primary} ankommen`), body: bi(`Use daylight to read signs, identify the legal footprint and place the vehicle once. Keep ${secondary} for a separately checked visit. Do not unload until the route back is still obvious.`, `Nutze das Tageslicht für Schilder, legale Fläche und einmaliges Abstellen. Bewahre ${secondary} für einen separat geprüften Besuch. Lade erst aus, wenn der Rückweg weiterhin eindeutig ist. So bleibt die Abfahrt auch bei Dunkelheit verständlich.`), sourceIds },
      { id: `${id}-observe`, timeHint: bi("After twilight", "Nach der Dämmerung"), title: bi("Observe without expanding the footprint", "Beobachten ohne die Fläche zu erweitern"), body: bi(`Let adaptation settle, keep light low and add only equipment that remains clear of shared movement and the route back to ${base}. Recheck wind, temperature and nearby activity before extending the session.`, `Lass die Augen anpassen, halte Licht niedrig und ergänze nur Ausrüstung ohne Behinderung gemeinsamer Wege und des Rückwegs nach ${base}. Prüfe Wind, Temperatur und Aktivität in der Nähe erneut, bevor du die Sitzung verlängerst.`), sourceIds },
      { id: `${id}-leave`, timeHint: bi("At the planned finish", "Zur geplanten Endzeit"), title: bi(`Return directly to ${base}`, `Direkt nach ${base} zurückkehren`), body: bi(`Count equipment, inspect the surface and leave before fatigue or changing weather makes a late detour tempting. A direct return is the final part of the plan, not an afterthought once the sky has been good.`, `Zähle die Ausrüstung, prüfe den Untergrund und fahre ab, bevor Müdigkeit oder Wetter einen späten Umweg verlockend machen. Die direkte Rückkehr ist der letzte Teil des Plans und kein nachträglicher Gedanke. Sie schützt Urteilskraft und einen einfachen nächsten Morgen.`), sourceIds },
    ] },
    fieldNotesTitle: bi(`Three limits specific to ${name}`, `Drei Grenzen speziell für ${name}`),
    fieldNotes: [
      { id: `${id}-access-note`, title: bi(`${name} access is dated information`, `Zugang in ${name} ist datierte Information`), body: bi(`${primary} is listed because an official source describes the visitor context. Recheck that source for the chosen date; the coordinate never grants entry, parking, camping or permission to cross a barrier.`, `${primary} ist aufgeführt, weil eine offizielle Quelle den Besucherrahmen beschreibt. Prüfe sie für das gewählte Datum erneut; die Koordinate gewährt weder Zutritt, Parken, Camping noch das Passieren einer Schranke.`), sourceIds },
      { id: `${id}-weather-note`, title: bi(`${name} has a live-weather veto`, `${name} hat ein Veto des Live-Wetters`), body: bi(`The monthly comparison cannot include every cloud, smoke, closure or local obstruction. Postpone whenever safe access and a calm return do not agree.`, `Der Monatsvergleich enthält nicht jede Wolke, jeden Rauch, jede Sperrung oder jedes lokale Hindernis. Verschiebe, sobald sicherer Zugang und ruhige Rückkehr nicht zusammenpassen.`), sourceIds },
      { id: `${id}-light-note`, title: bi(`Light changes ${primary}`, `Licht verändert ${primary}`), body: bi(`Prepare screens and vehicle lights before arrival. Use the lowest practical red-light level and keep it brief, downward and away from other observers.`, `Bereite Displays und Fahrzeuglicht vor der Ankunft vor. Nutze die niedrigste praktische Rotlichtstufe kurz, nach unten und weg von anderen Beobachtern. So bleibt die Dunkeladaption der Gruppe erhalten und der Ort ruhig.`), sourceIds },
    ],
    faq: [
      { question: bi(`Is ${primary} guaranteed to be open at night?`, `Ist ${primary} nachts garantiert offen?`), answer: bi(`No. Check the cited authority for the date, opening hours, permits, parking and temporary restrictions. If the answer is unclear, do not infer permission. A safe alternative is postponement rather than a late roadside search.`, `Nein. Prüfe die zitierte Verwaltung für Datum, Öffnung, Genehmigungen, Parken und temporäre Regeln. Bei Unklarheit darfst du keine Erlaubnis ableiten. Sicherer ist Verschieben statt eine späte Suche am Straßenrand.`), sourceIds },
      { question: bi(`Does the ${name} score describe tonight?`, `Beschreibt der Wert für ${name} die heutige Nacht?`), answer: bi(`It compares historical climate, darkness, elevation and reviewed access inputs. It does not include tonight's clouds, smoke, road surface or every local closure, so a live check remains necessary before you leave the accommodation.`, `Er vergleicht historische Eingaben zu Klima, Dunkelheit, Höhe und Zugang. Heutige Wolken, Rauch, Straßenoberfläche und jede lokale Sperrung fehlen; eine Live-Prüfung bleibt vor der Abfahrt von der Unterkunft nötig.`), sourceIds },
    ],
    sources: sourceRecords(item), lastReviewedAt: "2026-09-16",
  };
};

const makeTour = (item, index) => {
  const guide = makeGuide(item, index);
  const [id, name, , , , , , , , , stay, sites] = item;
  const sourceIds = guide.sources.map((source) => source.id);
  const primary = sites[0][1];
  const base = stay[1];
  return { version: 1, id: `${id}-one-site-night`, slug: `${id}-one-site-night`, destinationId: id, recommendedSiteId: sites[0][0], title: guide.tour.title, seoDescription: guide.seoDescription, standfirst: guide.standfirst, facts: [
    { label: bi("Observe at", "Beobachten an"), value: bi(primary, primary), sourceIds },
    { label: bi("Return base", "Rückkehrbasis"), value: bi(base, base), sourceIds },
    { label: bi("Arrival rule", "Ankunftsregel"), value: bi("Before sunset after a same-day access check", "Vor Sonnenuntergang nach Zugangskontrolle am selben Tag"), sourceIds },
    { label: bi("Separate alternative", "Getrennte Alternative"), value: bi(sites[1][1], sites[1][1]), sourceIds },
  ], blocks: [
    { id: `${id}-route-place`, kind: "prose", heading: bi(`Why this route stops at ${primary}`, `Warum diese Route an ${primary} endet`), paragraphs: { en: [`${guide.editorialAngle.en} The single-stop design protects attention, dark adaptation and the known return to ${base}.`, `Read signs and boundaries before unloading. A named place is useful only when its current visitor arrangement is understood.`], de: [`${guide.editorialAngle.de} Das Ein-Ort-Design schützt Aufmerksamkeit, Dunkeladaption und die bekannte Rückkehr nach ${base}.`, `Lies Schilder und Grenzen vor dem Ausladen. Ein benannter Ort hilft nur, wenn seine aktuelle Besucherregelung verstanden ist.`] }, sourceIds },
    { id: `${id}-route-timing`, kind: "schedule", heading: bi(`The sequence for ${name}`, `Die Reihenfolge für ${name}`), introduction: bi("Daylight arrival protects the night that follows.", "Ankunft bei Tageslicht schützt die folgende Nacht."), items: guide.tour.steps.slice(0, 3).map((step) => ({ time: step.timeHint, title: step.title, body: step.body, sourceIds })) },
    { id: `${id}-route-decision`, kind: "decisions", heading: bi(`Two outcomes are enough in ${name}`, `Zwei Ergebnisse genügen in ${name}`), introduction: bi("A supported night proceeds; an unsupported one stops.", "Eine bestätigte Nacht findet statt, eine unbestätigte endet."), items: [
      { label: bi("Access and return are confirmed", "Zugang und Rückkehr sind bestätigt"), body: bi(`Stay at ${primary}, keep the vehicle settled and return to ${base} by the route learned in daylight.`, `Bleibe an ${primary}, lasse das Fahrzeug stehen und kehre auf der bei Tageslicht erlernten Route nach ${base} zurück.`), sourceIds },
      { label: bi("A critical detail is missing", "Ein kritisches Detail fehlt"), body: bi("Postpone without adding an unverified roadside stop. That is a complete and responsible result.", "Verschiebe ohne unbestätigten Straßenhalt. Das ist ein vollständiges und verantwortungsvolles Ergebnis."), sourceIds },
    ] },
    { id: `${id}-route-warning`, kind: "note", heading: bi(`The non-negotiable ${name} boundary`, `Die unverhandelbare Grenze in ${name}`), body: bi(`Current authority rules take precedence over a clear sky, an attractive photograph or an old map pin.`, `Aktuelle Verwaltungsregeln haben Vorrang vor klarem Himmel, attraktivem Foto oder altem Kartenpin.`), sourceIds, tone: "warning" },
  ], sourceIds, lastReviewedAt: "2026-09-16" };
};

const destinations = read("data-config/sources/destinations.json");
const sites = read("data-config/sources/observation-sites.json");
const stays = read("data-config/sources/stay-areas.json");
const destinationImages = read("data-config/sources/destination-images.json");
const siteImages = read("data-config/sources/site-images.json");
const guides = read("data-config/editorial/destination-guides.json");
const tours = read("data-config/editorial/location-tours.json");
const upsert = (array, item, key = "id") => {
  const index = array.findIndex((value) => value[key] === item[key]);
  if (index < 0) array.push(item); else array[index] = item;
};

for (const [index, item] of candidates.entries()) {
  const [id, name, countryCode, countryName, continent, regions, timezone, priority, tags, affiliateQuery, stay, itemSites] = item;
  const observationSiteIds = itemSites.map((site) => site[0]);
  upsert(destinations, { id, slug: id, name, countryCode, countryName, continent, regionSlugs: regions, timezone, active: false, priority, tags, observationSiteIds, stayAreaIds: [stay[0]], affiliateQuery });
  for (const [siteId, siteName, lat, lon, elevationM, siteType, publicAccess, accessScore] of itemSites) {
    upsert(sites, { id: siteId, slug: siteId, destinationId: id, name: siteName, lat, lon, elevationM, siteType, publicAccess, accessScore, active: false, priority, certificationIds: [], notesSourceUrl: item[12][0], accessNotes: bi(`Use only the current published visitor arrangement for ${siteName}. Confirm opening, parking, hazards, permits and the return before travel; this coordinate is not permission to enter or camp.`, `Nutze für ${siteName} nur die aktuell veröffentlichte Besucherregelung. Bestätige Öffnung, Parken, Gefahren, Genehmigungen und Rückkehr vor der Fahrt; diese Koordinate ist keine Zutritts- oder Campingerlaubnis.`) });
    upsert(siteImages, { slug: siteId, status: "pending", overrideReason: "Awaiting a fully attributed CC0, CC BY, CC BY-SA, public-domain, or government-work image." }, "slug");
  }
  upsert(stays, { id: stay[0], destinationId: id, name: stay[1], lat: stay[2], lon: stay[3], affiliateQuery: `${stay[1]} ${countryName}`, observationSiteIds });
  upsert(destinationImages, { slug: id, status: "pending", overrideReason: "Awaiting a fully attributed CC0, CC BY, CC BY-SA, public-domain, or government-work image." }, "slug");
  upsert(guides, makeGuide(item, index), "slug");
  upsert(tours, makeTour(item, index), "slug");
}

write("data-config/sources/destinations.json", destinations);
write("data-config/sources/observation-sites.json", sites);
write("data-config/sources/stay-areas.json", stays);
write("data-config/sources/destination-images.json", destinationImages);
write("data-config/sources/site-images.json", siteImages);
write("data-config/editorial/destination-guides.json", guides);
write("data-config/editorial/location-tours.json", tours);
console.log(`Expanded catalog to ${destinations.length} destinations, ${sites.length} sites, ${guides.length} guides and ${tours.length} tours.`);
