import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const write = (relative, value) => fs.writeFileSync(path.join(root, relative), `${JSON.stringify(value, null, 2)}\n`);
const bi = (en, de) => ({ en, de });

const candidates = [
  {
    id: "joshua-tree", name: "Joshua Tree", countryCode: "US", countryName: "United States", continent: "north-america", regions: ["california", "north-america"], timezone: "America/Los_Angeles", priority: 91,
    tags: ["desert", "dark-sky", "national-park", "road-trip"], affiliateQuery: "Joshua Tree National Park California", stay: ["twentynine-palms", "Twentynine Palms", 34.1356, -116.0542],
    sites: [
      ["hidden-valley-joshua-tree", "Hidden Valley picnic area", 34.0124, -116.168, 1280, "park-picnic-area", "yes", 82, "https://www.nps.gov/jotr/planyourvisit/stargazing.htm"],
      ["cottonwood-joshua-tree", "Cottonwood Campground", 33.7458, -115.8014, 930, "campground", "limited", 76, "https://www.nps.gov/jotr/planyourvisit/campgrounds.htm"],
    ],
    source: [
      ["National Park Service", "Stargazing in Joshua Tree", "https://www.nps.gov/jotr/planyourvisit/stargazing.htm", "protected-area"],
      ["National Park Service", "Joshua Tree campgrounds", "https://www.nps.gov/jotr/planyourvisit/campgrounds.htm", "protected-area"],
      ["National Park Service", "Current conditions and alerts", "https://www.nps.gov/jotr/planyourvisit/conditions.htm", "public-agency"],
    ],
    title: bi("A desert night between Hidden Valley and Cottonwood", "Eine Wüstennacht zwischen Hidden Valley und Cottonwood"),
    opening: bi("Joshua Tree offers several legal places to look up after dark, but they solve different trips. Hidden Valley suits a shorter evening from the park's northern entrances. Cottonwood makes more sense when the southern campground is already part of the itinerary.", "Joshua Tree bietet mehrere legale Orte für eine Nachtbeobachtung, doch sie passen zu unterschiedlichen Reisen. Hidden Valley eignet sich für einen kürzeren Abend von den nördlichen Eingängen. Cottonwood ist sinnvoller, wenn der südliche Campingplatz ohnehin Teil der Route ist."),
    constraint: bi("Desert heat, scarce water, long driving distances and unlit roads remain the controlling risks. Parking at a named site does not permit roadside camping or movement into closed ground.", "Wüstenhitze, knappes Wasser, lange Fahrstrecken und unbeleuchtete Straßen bleiben die entscheidenden Risiken. Ein Parkplatz an einem genannten Ort erlaubt weder Straßenrand-Camping noch das Betreten gesperrter Flächen."),
    route: bi("Use Hidden Valley as a compact evening stop, or reserve Cottonwood and observe from the campground area without adding a cross-park drive after fatigue sets in.", "Nutze Hidden Valley als kompakten Abendstopp oder reserviere Cottonwood und beobachte im Bereich des Campingplatzes, ohne später müde noch quer durch den Park zu fahren."),
    conduct: bi("Stay on durable surfaces, shield every light and leave Joshua trees, rocks and nocturnal wildlife undisturbed.", "Bleibe auf robusten Flächen, schirme jedes Licht ab und lasse Joshua Trees, Felsen sowie nachtaktive Tiere ungestört."),
    fallback: bi("If alerts, heat or wind undermine the plan, keep the evening near the booked accommodation in Twentynine Palms rather than improvising a remote pull-out.", "Wenn Meldungen, Hitze oder Wind den Plan entwerten, bleibe nahe der gebuchten Unterkunft in Twentynine Palms, statt spontan eine abgelegene Haltebucht zu nutzen."),
  },
  {
    id: "sedona", name: "Sedona", countryCode: "US", countryName: "United States", continent: "north-america", regions: ["arizona", "north-america"], timezone: "America/Phoenix", priority: 86,
    tags: ["desert", "dark-sky-community", "accessible", "red-rock"], affiliateQuery: "Sedona Arizona", stay: ["sedona-town", "Sedona", 34.8697, -111.761],
    sites: [
      ["two-trees-observing-area", "Two Trees observing area", 34.858, -111.817, 1320, "community-observing-area", "yes", 80, "https://visitsedona.com/blog/stargazing-in-sedona/"],
      ["turkey-creek-trailhead-night", "Turkey Creek trailhead", 34.803, -111.857, 1250, "trailhead", "limited", 68, "https://www.fs.usda.gov/recarea/coconino/recarea/?recid=55330"],
    ],
    source: [
      ["Visit Sedona", "Stargazing in Sedona", "https://visitsedona.com/blog/stargazing-in-sedona/", "official-destination"],
      ["U.S. Forest Service", "Red Rock Ranger District", "https://www.fs.usda.gov/r03/coconino/recreation/red-rock-ranger-district", "public-agency"],
      ["DarkSky International", "Sedona Dark Sky Community", "https://darksky.org/places/sedona-dark-sky-community/", "nonprofit-certifier"],
    ],
    title: bi("Sedona after the trail crowds leave", "Sedona nach dem Ende des Wanderbetriebs"),
    opening: bi("Sedona's dark-sky status belongs to a living town surrounded by public land, not to a single fenced astronomy field. Two Trees is the simpler independent choice. Turkey Creek needs a separate check of forest notices, road condition and the exact place where a vehicle may remain.", "Sedonas Dark-Sky-Status gehört zu einer bewohnten Stadt inmitten öffentlicher Flächen und nicht zu einem einzelnen Astronomiefeld. Two Trees ist die einfachere unabhängige Wahl. Für Turkey Creek müssen Waldmeldungen, Straßenzustand und der legale Fahrzeugstandort separat geprüft werden."),
    constraint: bi("Parking pressure, private-property boundaries, monsoon storms and rough forest roads can change a seemingly easy plan. A scenic daytime trailhead is not automatically suitable after dark.", "Parkdruck, Privatgrundstücke, Monsungewitter und raue Forststraßen können einen scheinbar einfachen Plan verändern. Ein schöner Tages-Trailhead ist nicht automatisch nachts geeignet."),
    route: bi("Eat and refuel in town, reach Two Trees before sunset, identify the return road in daylight and keep the session short enough for a calm drive back.", "Iss und tanke in der Stadt, erreiche Two Trees vor Sonnenuntergang, erkenne den Rückweg bei Tageslicht und halte die Sitzung kurz genug für eine ruhige Rückfahrt."),
    conduct: bi("Keep red-rock pull-outs clear, avoid residential spill light and never create a new parking bay on fragile desert soil.", "Halte Haltebuchten an den roten Felsen frei, vermeide Licht in Wohngebiete und lege niemals neue Parkflächen auf empfindlichem Wüstenboden an."),
    fallback: bi("Cloud or a closed forest road should move the evening back to town, where a brief naked-eye session is safer than searching unfamiliar tracks at night.", "Wolken oder eine gesperrte Forststraße verlagern den Abend zurück in die Stadt. Eine kurze Beobachtung mit bloßem Auge ist dort sicherer als die Suche auf unbekannten Wegen bei Nacht."),
  },
  {
    id: "acadia", name: "Acadia", countryCode: "US", countryName: "United States", continent: "north-america", regions: ["maine", "north-america"], timezone: "America/New_York", priority: 85,
    tags: ["coast", "national-park", "dark-sky", "maritime"], affiliateQuery: "Acadia National Park Maine", stay: ["bar-harbor", "Bar Harbor", 44.3876, -68.2039],
    sites: [
      ["seawall-acadia", "Seawall picnic area", 44.249, -68.299, 8, "coastal-picnic-area", "yes", 82, "https://www.nps.gov/acad/planyourvisit/stargazing.htm"],
      ["jordan-pond-acadia", "Jordan Pond north lot", 44.3204, -68.2546, 85, "park-parking-area", "limited", 72, "https://www.nps.gov/acad/planyourvisit/park-loop-road.htm"],
    ],
    source: [
      ["National Park Service", "Stargazing in Acadia", "https://www.nps.gov/acad/planyourvisit/stargazing.htm", "protected-area"],
      ["National Park Service", "Park Loop Road", "https://www.nps.gov/acad/planyourvisit/park-loop-road.htm", "public-agency"],
      ["National Park Service", "Acadia current conditions", "https://www.nps.gov/acad/planyourvisit/conditions.htm", "public-agency"],
    ],
    title: bi("A coastal sky from Seawall, without a Cadillac detour", "Küstenhimmel an Seawall ohne Cadillac-Umweg"),
    opening: bi("Acadia rewards a site chosen for the actual night rather than the most famous summit. Seawall provides an open southwest coast and a straightforward return toward Southwest Harbor. Jordan Pond can work when the park road and parking arrangements have been checked for that date.", "In Acadia lohnt sich ein Ort, der zur tatsächlichen Nacht passt, mehr als der berühmteste Gipfel. Seawall bietet eine offene Südwestküste und eine klare Rückfahrt Richtung Southwest Harbor. Jordan Pond funktioniert, wenn Parkstraße und Parkregeln für das Datum geprüft sind."),
    constraint: bi("Cadillac Summit Road has timed and nightly restrictions, while fog, sea spray and wildlife make improvised coastal movement poor practice.", "Die Cadillac Summit Road hat zeitliche und nächtliche Beschränkungen. Nebel, Gischt und Wildtiere machen spontane Bewegungen an der Küste unvernünftig."),
    route: bi("Base the evening around Seawall, inspect the shoreline boundary before dark and return on the same road without chasing breaks in cloud across Mount Desert Island.", "Plane den Abend um Seawall, prüfe die Küstengrenze vor Dunkelheit und fahre auf derselben Straße zurück, statt Wolkenlücken über Mount Desert Island zu verfolgen."),
    conduct: bi("Use the established picnic and parking footprint, keep off wet rocks and protect the quiet of nearby campgrounds and homes.", "Nutze bestehende Picknick- und Parkflächen, bleibe von nassen Felsen fern und schütze die Ruhe naher Campingplätze und Häuser."),
    fallback: bi("Dense fog is a reason to end the coastal session early, not to climb higher on a restricted summit road.", "Dichter Nebel ist ein Grund, die Küstensitzung früh zu beenden, und kein Anlass, auf einer beschränkten Gipfelstraße höher zu fahren."),
  },
  {
    id: "grand-canyon", name: "Grand Canyon", countryCode: "US", countryName: "United States", continent: "north-america", regions: ["arizona", "north-america"], timezone: "America/Phoenix", priority: 94,
    tags: ["high-desert", "national-park", "dark-sky", "road-trip"], affiliateQuery: "Grand Canyon South Rim Arizona", stay: ["grand-canyon-village", "Grand Canyon Village", 36.0544, -112.1401],
    sites: [
      ["mather-point-night", "Mather Point", 36.0613, -112.107, 2160, "rim-viewpoint", "yes", 84, "https://www.nps.gov/grca/learn/nature/night-skies.htm"],
      ["desert-view-night", "Desert View", 36.0409, -111.8262, 2265, "rim-viewpoint", "limited", 75, "https://www.nps.gov/grca/planyourvisit/desert-view.htm"],
    ],
    source: [
      ["National Park Service", "Grand Canyon night skies", "https://www.nps.gov/grca/learn/nature/night-skies.htm", "protected-area"],
      ["National Park Service", "Desert View", "https://www.nps.gov/grca/planyourvisit/desert-view.htm", "protected-area"],
      ["National Park Service", "South Rim current conditions", "https://www.nps.gov/grca/planyourvisit/conditions.htm", "public-agency"],
    ],
    title: bi("A South Rim observing night with the edge kept visible", "Eine Beobachtungsnacht am South Rim mit sichtbarer Kante"),
    opening: bi("Grand Canyon darkness is exceptional, yet the rim itself makes careless night movement unacceptable. Mather Point is the practical default because its established visitor infrastructure is close to Grand Canyon Village. Desert View belongs to a deliberate east-rim itinerary, not a late chase for a darker horizon.", "Die Dunkelheit am Grand Canyon ist außergewöhnlich, doch die Abbruchkante verbietet unvorsichtige Nachtbewegung. Mather Point ist wegen der bestehenden Infrastruktur nahe Grand Canyon Village die praktische Standardwahl. Desert View gehört zu einer geplanten Ost-Rim-Route und nicht zu einer späten Jagd nach dunklerem Horizont."),
    constraint: bi("Cliff edges, altitude, winter ice, summer storms and long night drives outweigh small differences in modeled sky quality between overlooks.", "Abbruchkanten, Höhe, Wintereis, Sommergewitter und lange Nachtfahrten wiegen schwerer als kleine Unterschiede der modellierten Himmelsqualität zwischen Aussichtspunkten."),
    route: bi("Walk the Mather Point approach while it is light, choose a position behind established barriers and return to the village before cold or fatigue changes judgement.", "Gehe den Zugang zu Mather Point bei Licht ab, wähle einen Platz hinter bestehenden Barrieren und kehre ins Village zurück, bevor Kälte oder Müdigkeit das Urteil verändern."),
    conduct: bi("Never step beyond railings for a photograph, keep paths open and use only shielded light directed at the ground.", "Steige für ein Foto niemals über Geländer, halte Wege offen und nutze nur abgeschirmtes, nach unten gerichtetes Licht."),
    fallback: bi("If wind, ice or lightning develops, use the nearby indoor and lodging plan rather than moving to another rim viewpoint in darkness.", "Bei Wind, Eis oder Blitz nutze den nahen Innenraum- und Unterkunftsplan, statt in der Dunkelheit zu einem anderen Rim-Aussichtspunkt zu wechseln."),
  },
  {
    id: "bryce-canyon", name: "Bryce Canyon", countryCode: "US", countryName: "United States", continent: "north-america", regions: ["utah", "north-america"], timezone: "America/Denver", priority: 90,
    tags: ["high-altitude", "national-park", "dark-sky", "cold"], affiliateQuery: "Bryce Canyon National Park Utah", stay: ["bryce-canyon-city", "Bryce Canyon City", 37.6283, -112.1677],
    sites: [
      ["sunset-point-bryce", "Sunset Point", 37.6283, -112.178, 2435, "rim-viewpoint", "yes", 82, "https://www.nps.gov/brca/planyourvisit/astronomyprograms.htm"],
      ["paria-view-bryce", "Paria View", 37.6347, -112.1645, 2470, "rim-viewpoint", "limited", 72, "https://www.nps.gov/brca/planyourvisit/conditions.htm"],
    ],
    source: [
      ["National Park Service", "Astronomy programs at Bryce Canyon", "https://www.nps.gov/brca/planyourvisit/astronomyprograms.htm", "protected-area"],
      ["National Park Service", "Bryce Canyon safety", "https://www.nps.gov/brca/planyourvisit/safety.htm", "public-agency"],
      ["National Park Service", "Bryce Canyon conditions", "https://www.nps.gov/brca/planyourvisit/conditions.htm", "public-agency"],
    ],
    title: bi("Cold air and a fixed rim at Bryce Canyon", "Kalte Luft und eine feste Rim-Position im Bryce Canyon"),
    opening: bi("Bryce Canyon sits high enough for summer evenings to feel cold and for winter footing to become the decisive issue. Sunset Point gives an established approach close to park services. Paria View is an alternative only when its access and surface are clearly open.", "Bryce Canyon liegt hoch genug, dass selbst Sommerabende kalt werden und Winteruntergrund die Entscheidung bestimmt. Sunset Point bietet einen etablierten Zugang nahe der Parkservices. Paria View ist nur dann eine Alternative, wenn Zufahrt und Fläche eindeutig offen sind."),
    constraint: bi("The amphitheatre rim, freezing temperatures, lightning and seasonal road conditions require a conservative fixed-site plan.", "Amphitheaterkante, Frost, Blitz und saisonale Straßenzustände verlangen einen konservativen Plan an einem festen Ort."),
    route: bi("Park once at Sunset Point, identify the paved return before twilight and observe from the established area without entering hoodoo trails at night.", "Parke einmal am Sunset Point, erkenne den befestigten Rückweg vor der Dämmerung und beobachte im etablierten Bereich, ohne nachts Hoodoo-Wege zu betreten."),
    conduct: bi("Respect ranger programs, keep equipment away from walkways and preserve other visitors' dark adaptation with minimal red light.", "Respektiere Rangerprogramme, halte Ausrüstung von Wegen fern und schütze die Dunkeladaption anderer mit minimalem Rotlicht."),
    fallback: bi("Snow, ice or electrical storms should end the rim visit; a lower roadside alternative is not automatically safer without an official opening notice.", "Schnee, Eis oder Gewitter beenden den Rim-Besuch. Eine niedrigere Straßenalternative ist ohne offizielle Öffnungsmeldung nicht automatisch sicherer."),
  },
];

// The remaining entries are kept separate so the reviewable core fields above stay readable.
const compact = [
  ["capitol-reef","Capitol Reef","US","United States","north-america",["utah","north-america"],"America/Denver",89,["desert","national-park","dark-sky"],"Capitol Reef National Park Utah",["torrey","Torrey",38.298,-111.419],[["panorama-point-capitol-reef","Panorama Point",38.288,-111.244,1770,"desert-viewpoint","yes",82,"https://www.nps.gov/care/learn/nature/lightscape.htm"],["fruita-campground-night","Fruita Campground",38.283,-111.248,1680,"campground","limited",76,"https://www.nps.gov/care/planyourvisit/campgrounds.htm"]],["https://www.nps.gov/care/learn/nature/lightscape.htm","https://www.nps.gov/care/planyourvisit/campgrounds.htm","https://www.nps.gov/care/planyourvisit/conditions.htm"],"Panorama Point without a night drive through the Waterpocket Fold","Panorama Point ohne Nachtfahrt durch die Waterpocket Fold","Capitol Reef combines a dark central valley with long roads that become less useful after fatigue. Panorama Point is the independent observing choice. Fruita Campground works for guests who already hold a legal campsite.","Capitol Reef verbindet ein dunkles Zentraltal mit langen Straßen, die bei Müdigkeit an Nutzen verlieren. Panorama Point ist die unabhängige Beobachtungswahl. Fruita Campground eignet sich für Gäste mit legalem Stellplatz.","Flash floods, wildlife, rough side roads and limited services make late route changes a poor bargain.","Sturzfluten, Wildtiere, raue Nebenstraßen und begrenzte Services machen späte Routenwechsel unvernünftig.","Reach Panorama Point before sunset, remain on the established surface and return toward Torrey on the same paved road.","Erreiche Panorama Point vor Sonnenuntergang, bleibe auf der etablierten Fläche und kehre auf derselben Asphaltstraße Richtung Torrey zurück.","Keep orchards, campsites and historic structures free of stray light and avoid blocking pull-outs.","Halte Obstgärten, Campingplätze und historische Gebäude frei von Streulicht und blockiere keine Haltebuchten.","If storm cells or road alerts appear, stay in Torrey and do not search for an improvised position in the Fold.","Bei Gewitterzellen oder Straßenmeldungen bleibe in Torrey und suche keine spontane Position in der Fold."],
  ["arches","Arches","US","United States","north-america",["utah","north-america"],"America/Denver",92,["desert","national-park","dark-sky"],"Arches National Park Moab Utah",["moab","Moab",38.5733,-109.5498],[["balanced-rock-night","Balanced Rock",38.7006,-109.5637,1580,"desert-viewpoint","yes",84,"https://www.nps.gov/arch/learn/nature/night-sky.htm"],["panorama-point-arches","Panorama Point",38.734,-109.504,1535,"desert-viewpoint","yes",80,"https://www.nps.gov/arch/learn/nature/night-sky.htm"]],["https://www.nps.gov/arch/learn/nature/night-sky.htm","https://www.nps.gov/arch/planyourvisit/traffic.htm","https://www.nps.gov/arch/planyourvisit/conditions.htm"],"One paved Arches viewpoint after the traffic thins","Ein befestigter Aussichtspunkt in Arches nach dem Tagesverkehr","Arches is busiest by day, while its best independent astronomy plan is deliberately small. Balanced Rock and Panorama Point both have established parking; choose one before entering and resist site-hopping after dark.","Arches ist tagsüber stark besucht, während der beste unabhängige Astronomieplan bewusst klein bleibt. Balanced Rock und Panorama Point besitzen etablierte Parkplätze. Wähle einen vor der Einfahrt und verzichte nachts auf Standortwechsel.","Traffic, limited parking, exposed desert weather and wildlife on the park road control the evening more than a minor darkness difference.","Verkehr, begrenzte Parkplätze, exponiertes Wüstenwetter und Wildtiere auf der Parkstraße bestimmen den Abend stärker als kleine Dunkelheitsunterschiede.","Use Balanced Rock for a shorter walk and Panorama Point only when its parking is confirmed, then return directly to Moab.","Nutze Balanced Rock für einen kurzen Weg und Panorama Point nur bei bestätigtem Parkplatz, danach fahre direkt nach Moab zurück.","Do not climb formations, leave equipment on cryptobiotic soil or aim white light toward other observers.","Klettere nicht auf Formationen, stelle Ausrüstung nicht auf kryptobiotischen Boden und richte kein Weißlicht auf andere Beobachter.","Crowded parking or a storm warning means leaving the park rather than circling between overlooks.","Voller Parkplatz oder Gewitterwarnung bedeutet, den Park zu verlassen, statt zwischen Aussichtspunkten zu kreisen."],
  ["badlands","Badlands","US","United States","north-america",["south-dakota","north-america"],"America/Denver",86,["prairie","national-park","dark-sky"],"Badlands National Park South Dakota",["wall-south-dakota","Wall",43.992,-102.241],[["cedar-pass-badlands","Cedar Pass Campground",43.747,-101.941,760,"campground","limited",78,"https://www.nps.gov/badl/planyourvisit/camping.htm"],["pinnacles-overlook-badlands","Pinnacles Overlook",43.886,-102.235,970,"rim-viewpoint","yes",80,"https://www.nps.gov/badl/planyourvisit/night-sky-viewing.htm"]],["https://www.nps.gov/badl/planyourvisit/night-sky-viewing.htm","https://www.nps.gov/badl/planyourvisit/camping.htm","https://www.nps.gov/badl/planyourvisit/conditions.htm"],"Prairie weather and one chosen overlook in Badlands","Präriewetter und ein gewählter Aussichtspunkt in Badlands","Badlands exposes an enormous sky, but also wind, lightning, bison and abrupt drop-offs. Pinnacles Overlook serves an independent visit. Cedar Pass is preferable when a booked campsite removes the need for a late drive.","Badlands öffnet einen riesigen Himmel, aber auch Wind, Blitz, Bisons und abrupte Kanten. Pinnacles Overlook eignet sich unabhängig. Cedar Pass ist besser, wenn ein gebuchter Stellplatz die späte Fahrt vermeidet.","Severe storms, wildlife on roads and unguarded terrain can turn a clear-looking evening unsafe quickly.","Starke Gewitter, Tiere auf Straßen und ungesichertes Gelände können einen klar wirkenden Abend rasch unsicher machen.","Arrive at Pinnacles in daylight, use the formal overlook and return toward Wall without stopping on narrow shoulders.","Erreiche Pinnacles bei Tageslicht, nutze den formalen Aussichtspunkt und fahre ohne Stopps auf schmalen Seitenstreifen Richtung Wall zurück.","Stay behind established edges, give wildlife a wide berth and leave the prairie quiet.","Bleibe hinter etablierten Kanten, halte großen Abstand zu Wildtieren und lasse die Prärie ruhig.","Lightning or animals near the parking area ends the session; a vehicle is shelter only when official safety guidance supports it.","Blitze oder Tiere nahe dem Parkplatz beenden die Sitzung. Ein Fahrzeug ist nur Schutz, wenn offizielle Sicherheitshinweise dies stützen."],
  ["waterton-lakes","Waterton Lakes","CA","Canada","north-america",["alberta","north-america"],"America/Edmonton",84,["mountain","dark-sky","national-park"],"Waterton Lakes National Park Alberta",["waterton-park","Waterton Park",49.05,-113.91],[["townsite-campground-waterton","Townsite Campground",49.0507,-113.907,1280,"campground","limited",76,"https://parks.canada.ca/pn-np/ab/waterton/activ/camping"],["cameron-bay-waterton","Cameron Bay day-use area",49.027,-114.041,1290,"lakeside-day-use", "limited",68,"https://parks.canada.ca/pn-np/ab/waterton/visit/heures-hours"]],["https://parks.canada.ca/pn-np/ab/waterton/activ/experiences/ciel-sky","https://parks.canada.ca/pn-np/ab/waterton/activ/camping","https://parks.canada.ca/pn-np/ab/waterton/visit/conditions"],"A Waterton night that stays close to the townsite","Eine Waterton-Nacht nahe dem Townsite","Waterton's mountain darkness comes with wind, wildlife and seasonal closures. A reserved Townsite campsite offers the most defensible overnight base. Cameron Bay needs confirmation that the day-use area and approach remain available after dark.","Watertons Bergdunkelheit bringt Wind, Wildtiere und saisonale Sperren mit sich. Ein reservierter Townsite-Stellplatz bietet die verlässlichste Nachtbasis. Für Cameron Bay muss bestätigt sein, dass Tagesfläche und Zufahrt nachts verfügbar bleiben.","Bear activity, strong gusts, wildfire measures and winter shutdowns override every astronomy score.","Bärenaktivität, starke Böen, Waldbrandmaßnahmen und Wintersperren stehen über jedem Astronomiewert.","Observe from the booked campground footprint or a confirmed lakeside area, then return on the known townsite route.","Beobachte innerhalb des gebuchten Campingbereichs oder an einer bestätigten Seeuferfläche und kehre auf der bekannten Townsite-Route zurück.","Store food correctly, avoid shoreline vegetation and never approach wildlife for a night photograph.","Lagere Essen korrekt, meide Ufervegetation und nähere dich für Nachtfotos niemals Wildtieren.","Wind or wildlife near the site moves the session into shelter; it does not justify a drive onto a seasonal road.","Wind oder Wildtiere nahe dem Ort verlagern die Sitzung in den Schutz und rechtfertigen keine Fahrt auf eine saisonale Straße."],
  ["wood-buffalo","Wood Buffalo","CA","Canada","north-america",["northwest-territories","north-america"],"America/Yellowknife",93,["boreal","dark-sky","remote"],"Wood Buffalo National Park Canada",["fort-smith","Fort Smith",60.005,-111.884],[["pine-lake-wood-buffalo","Pine Lake Campground",60.728,-112.257,225,"campground","limited",74,"https://parks.canada.ca/pn-np/nt/woodbuffalo/activ/camping"],["salt-river-day-use","Salt River day-use area",60.117,-112.123,205,"day-use-area","limited",64,"https://parks.canada.ca/pn-np/nt/woodbuffalo/visit/heures-hours"]],["https://parks.canada.ca/pn-np/nt/woodbuffalo/nature/science_conservation/ciel-sky","https://parks.canada.ca/pn-np/nt/woodbuffalo/activ/camping","https://parks.canada.ca/pn-np/nt/woodbuffalo/securite-safety"],"Wood Buffalo from a booked boreal base","Wood Buffalo von einer gebuchten borealen Basis","Wood Buffalo's scale is the attraction and the main planning hazard. Pine Lake Campground gives a legal base with a known road. Salt River is an alternative only after current hours, road and wildlife advice are confirmed.","Die Größe von Wood Buffalo ist Attraktion und zentrales Planungsrisiko zugleich. Pine Lake Campground bietet eine legale Basis an bekannter Straße. Salt River ist nur nach Bestätigung von Zeiten, Straße und Wildtierhinweisen eine Alternative.","Remote communications, bison, bears, wildfire smoke and long distances make independent rescue assumptions unacceptable.","Abgelegene Kommunikation, Bisons, Bären, Waldbrandrauch und lange Distanzen machen selbst erfundene Rettungsannahmen unzulässig.","Book Pine Lake, download the route and alerts in Fort Smith, then keep astronomy beside camp rather than roaming the park road.","Buche Pine Lake, lade Route und Meldungen in Fort Smith herunter und halte die Astronomie am Camp, statt nachts die Parkstraße abzufahren.","Follow all food-storage and wildlife rules, keep generators and light restrained and leave shorelines intact.","Befolge alle Regeln zu Essen und Wildtieren, begrenze Generatoren und Licht und lasse Ufer intakt.","Smoke, road damage or wildlife activity cancels the remote leg; Fort Smith is the fallback, not another unsigned track.","Rauch, Straßenschäden oder Wildtieraktivität streichen den abgelegenen Abschnitt. Fort Smith ist die Alternative, nicht ein anderer unmarkierter Weg."],
];

for (const row of compact) {
  const [id,name,countryCode,countryName,continent,regions,timezone,priority,tags,affiliateQuery,stay,sites,urls,titleEn,titleDe,openingEn,openingDe,constraintEn,constraintDe,routeEn,routeDe,conductEn,conductDe,fallbackEn,fallbackDe] = row;
  candidates.push({ id,name,countryCode,countryName,continent,regions,timezone,priority,tags,affiliateQuery,stay,sites,
    source: [["Official park authority",`${name} night-sky guidance`,urls[0],"protected-area"],["Official park authority",`${name} access and visitor rules`,urls[1],"public-agency"],["Official park authority",`${name} current conditions`,urls[2],"public-agency"]],
    title: bi(titleEn,titleDe), opening: bi(openingEn,openingDe), constraint: bi(constraintEn,constraintDe), route: bi(routeEn,routeDe), conduct: bi(conductEn,conductDe), fallback: bi(fallbackEn,fallbackDe) });
}

const additional = [
  ["kejimkujik","Kejimkujik","CA","Canada","north-america",["nova-scotia","north-america"],"America/Halifax",83,["forest","dark-sky","national-park","lake"],"Kejimkujik National Park Nova Scotia",["annapolis-royal","Annapolis Royal",44.741,-65.515],[["jeremys-bay-kejimkujik","Jeremy's Bay Campground",44.408,-65.245,95,"campground","limited",78,"https://parks.canada.ca/pn-np/ns/kejimkujik/activ/camping"],["sky-circle-kejimkujik","Kejimkujik Sky Circle",44.405,-65.25,90,"astronomy-area","limited",72,"https://parks.canada.ca/pn-np/ns/kejimkujik/activ/decouverte-tours/etoile-star"]],["https://parks.canada.ca/pn-np/ns/kejimkujik/activ/decouverte-tours/etoile-star","https://parks.canada.ca/pn-np/ns/kejimkujik/activ/camping","https://parks.canada.ca/pn-np/ns/kejimkujik/visit/conditions"],"A forest night at Kejimkujik's Sky Circle","Eine Waldnacht am Sky Circle in Kejimkujik","Kejimkujik places its astronomy inside a forest and lake landscape rather than on an exposed summit. The Sky Circle is the clearest programme-led choice. Jeremy's Bay works for campers who can keep the session inside their legal overnight plan.","Kejimkujik legt seine Astronomie in eine Wald- und Seenlandschaft statt auf einen exponierten Gipfel. Der Sky Circle ist die klarste programmgebundene Wahl. Jeremy's Bay passt für Camper, die die Sitzung in ihren legalen Übernachtungsplan integrieren.","Seasonal operations, insects, fog, wildlife and wooded navigation make a confirmed programme or campsite more valuable than a random clearing.","Saisonbetrieb, Insekten, Nebel, Wildtiere und Navigation im Wald machen ein bestätigtes Programm oder einen Stellplatz wertvoller als irgendeine Lichtung.","Check the Sky Circle schedule or reserve Jeremy's Bay, walk the short route before dusk and keep the return entirely within the known campground network.","Prüfe den Sky-Circle-Termin oder reserviere Jeremy's Bay, gehe die kurze Route vor der Dämmerung und halte den Rückweg vollständig im bekannten Campingnetz.","Protect Mi'kmaw cultural context, quiet hours, shoreline habitat and other campers' dark adaptation.","Respektiere Mi'kmaw-Kulturkontext, Ruhezeiten, Uferlebensräume und die Dunkeladaption anderer Camper.","A cancelled programme or wet, foggy forest moves the evening under shelter instead of to an unmarked lakeshore.","Ein abgesagtes Programm oder nasser, nebliger Wald verlagert den Abend in den Schutz statt an ein unmarkiertes Ufer."],
  ["mayo-dark-sky","Mayo Dark Sky Park","IE","Ireland","europe",["county-mayo","europe"],"Europe/Dublin",82,["peatland","dark-sky","atlantic","accessible"],"Mayo Dark Sky Park Ireland",["newport-mayo","Newport, County Mayo",53.886,-9.546],[["claggan-mountain-coastal-trail","Claggan Mountain Coastal Trail",53.95745,-9.79335,20,"coastal-trailhead","yes",80,"https://www.mayodarkskypark.ie/visit/"],["brogan-carroll-bothy","Brogan Carroll Bothy",53.98932,-9.57282,90,"dark-sky-viewpoint","yes",78,"https://www.mayodarkskypark.ie/visit/"]],["https://www.mayodarkskypark.ie/visit/","https://www.mayodarkskypark.ie/events/","https://www.wildnephinnationalpark.ie/"],"An Atlantic dark-sky night with a dry return","Eine Atlantik-Dark-Sky-Nacht mit trockenem Rückweg","Mayo's official viewing points sit in a wet Atlantic landscape where low elevation does not mean simple conditions. Claggan offers a coastal approach. Brogan Carroll Bothy shifts the experience inland and should be chosen before departure, not after cloud arrives.","Mayos offizielle Aussichtspunkte liegen in einer nassen Atlantiklandschaft, in der geringe Höhe keine einfachen Bedingungen bedeutet. Claggan bietet einen Küstenzugang. Brogan Carroll Bothy verlagert das Erlebnis ins Inland und wird vor der Abfahrt gewählt, nicht erst bei Wolken.","Fast showers, saturated ground, wind and weak mobile coverage can matter more than the climatological monthly score.","Schnelle Schauer, durchnässter Boden, Wind und schwacher Mobilfunk können wichtiger sein als der klimatologische Monatswert.","Start from Newport with offline directions, inspect the chosen path in daylight and set a firm return time before rain reduces visibility.","Starte in Newport mit Offline-Navigation, prüfe den gewählten Weg bei Tageslicht und setze eine feste Rückkehrzeit, bevor Regen die Sicht mindert.","Remain on signed routes, close gates, keep peat and coastal vegetation intact and direct light away from homes.","Bleibe auf beschilderten Routen, schließe Tore, schütze Torf und Küstenvegetation und richte Licht von Häusern weg.","When Atlantic cloud closes in, a village-based evening is the sensible fallback; moving between remote sites rarely restores a useful sky.","Wenn Atlantikwolken schließen, ist ein Abend im Ort die sinnvolle Alternative. Wechsel zwischen abgelegenen Orten bringt selten einen brauchbaren Himmel zurück."],
  ["eryri","Eryri","GB","United Kingdom","europe",["wales","europe"],"Europe/London",84,["mountain","dark-sky","national-park","cloud-variable"],"Eryri Snowdonia Wales",["beddgelert","Beddgelert",53.011,-4.101],[["llyn-y-dywarchen","Llyn y Dywarchen",53.074,-4.146,250,"lake-viewpoint","yes",78,"https://snowdonia.gov.wales/discover/dark-skies/"],["bwlch-y-groes-dark-sky","Bwlch y Groes",52.715,-3.582,545,"mountain-pass","limited",60,"https://snowdonia.gov.wales/discover/dark-skies/"]],["https://snowdonia.gov.wales/discover/dark-skies/","https://snowdonia.gov.wales/visit/plan-your-visit/","https://snowdonia.gov.wales/visit/safety/"],"Eryri from a lake edge, not a summit at night","Eryri vom Seeufer statt vom Gipfel bei Nacht","Eryri does not require a night summit to produce a powerful sky. Llyn y Dywarchen offers a lower, legible landscape. Bwlch y Groes is exposed and only belongs in a plan backed by current road, weather and parking information.","Eryri braucht keinen Nachtgipfel für einen eindrucksvollen Himmel. Llyn y Dywarchen bietet eine niedrigere, lesbare Landschaft. Bwlch y Groes ist exponiert und gehört nur in einen Plan mit aktuellen Straßen-, Wetter- und Parkinformationen.","Mountain weather, narrow roads, livestock and water edges make a daytime reconnaissance essential even for short sessions.","Bergwetter, schmale Straßen, Weidetiere und Wasserkanten machen eine Erkundung bei Tageslicht selbst für kurze Sitzungen notwendig.","Base in Beddgelert, use Llyn y Dywarchen as the fixed destination and avoid linking several passes after dark.","Nutze Beddgelert als Basis, Llyn y Dywarchen als festen Zielort und verbinde nachts nicht mehrere Pässe.","Park only where permitted, leave gates as found and keep light and noise away from farms and wildlife.","Parke nur erlaubt, hinterlasse Tore wie vorgefunden und halte Licht sowie Lärm von Höfen und Wildtieren fern.","Rain, fog or standing water means returning to Beddgelert; a higher road is not a reliable escape from Welsh weather.","Regen, Nebel oder stehendes Wasser bedeuten die Rückkehr nach Beddgelert. Eine höhere Straße ist kein verlässlicher Ausweg aus walisischem Wetter."],
  ["yorkshire-dales","Yorkshire Dales","GB","United Kingdom","europe",["england","europe"],"Europe/London",80,["upland","dark-sky","villages","accessible"],"Yorkshire Dales National Park England",["hawes","Hawes",54.304,-2.202],[["hawes-dark-sky","Dales Countryside Museum, Hawes",54.303,-2.201,255,"visitor-centre-grounds","limited",76,"https://www.yorkshiredales.org.uk/things-to-do/whats-on/dark-skies/"],["malham-national-park-centre","Malham National Park Centre",54.061,-2.153,205,"visitor-centre-grounds","limited",74,"https://www.yorkshiredales.org.uk/park-authority/living-and-working/planning-policy/dark-skies/"]],["https://www.yorkshiredales.org.uk/things-to-do/whats-on/dark-skies/","https://www.yorkshiredales.org.uk/park-authority/living-and-working/planning-policy/dark-skies/","https://www.yorkshiredales.org.uk/plan-your-visit/essential-information/"],"A Dales evening anchored to a village","Ein Dales-Abend mit fester Dorfbasis","The Yorkshire Dales are easiest to use when astronomy is tied to a village and a confirmed event or visitor-centre arrangement. Hawes offers that relationship clearly. Malham is a separate base, not a second stop on the same late-night circuit.","Die Yorkshire Dales lassen sich am besten nutzen, wenn Astronomie an ein Dorf und eine bestätigte Veranstaltung oder Besucherzentrum-Regelung gebunden ist. Hawes bietet diese Verbindung klar. Malham ist eine eigene Basis und kein zweiter Stopp derselben späten Runde.","Dry-stone walls, livestock, narrow lanes, cloud and private land boundaries punish improvised roadside observing.","Trockenmauern, Weidetiere, schmale Gassen, Wolken und Privatgrundstücke bestrafen spontane Straßenrandbeobachtung.","Stay in Hawes, confirm whether the museum grounds or an official event can be used and walk back within the settled area.","Übernachte in Hawes, bestätige die Nutzbarkeit des Museumsgeländes oder einer offiziellen Veranstaltung und gehe innerhalb des Ortes zurück.","Never block farm access, climb walls or direct lights into houses; public rights of way do not create a camping right.","Blockiere niemals Hofzufahrten, klettere nicht über Mauern und richte kein Licht in Häuser. Öffentliche Wege schaffen kein Campingrecht.","Low cloud should turn the evening into a village stay rather than a drive through unfamiliar dales looking for a gap.","Tiefe Wolken machen den Abend zu einem Aufenthalt im Dorf statt zu einer Fahrt durch unbekannte Dales auf der Suche nach einer Lücke."],
  ["south-downs","South Downs","GB","United Kingdom","europe",["england","europe"],"Europe/London",79,["chalk-downland","dark-sky","accessible","near-city"],"South Downs National Park England",["petersfield","Petersfield",51.005,-0.933],[["old-winchester-hill","Old Winchester Hill",50.978,-1.088,198,"hilltop-car-park","limited",70,"https://www.southdowns.gov.uk/dark-night-skies/where-to-stargaze/"],["iping-common-dark-sky","Iping Common",50.995,-0.784,55,"nature-reserve-car-park","limited",66,"https://www.southdowns.gov.uk/dark-night-skies/where-to-stargaze/"]],["https://www.southdowns.gov.uk/dark-night-skies/where-to-stargaze/","https://www.southdowns.gov.uk/dark-night-skies/","https://www.southdowns.gov.uk/getting-around/"],"A South Downs session that respects the last mile","Eine South-Downs-Sitzung mit Respekt für den letzten Kilometer","South Downs darkness exists close to towns, villages and sensitive chalk habitat. Old Winchester Hill gives elevation and an official discovery-site context. Iping Common is lower and ecologically delicate, so current parking and reserve guidance must be read literally.","Die Dunkelheit der South Downs liegt nahe an Städten, Dörfern und empfindlichem Kalkrasen. Old Winchester Hill bietet Höhe und den Kontext eines offiziellen Discovery Site. Iping Common liegt tiefer und ist ökologisch sensibel, daher gelten aktuelle Park- und Reservatshinweise wörtlich.","Car-park gates, residents, livestock, muddy paths and nature-reserve restrictions decide whether the final kilometre works.","Parkplatztore, Anwohner, Weidetiere, schlammige Wege und Naturschutzregeln entscheiden, ob der letzte Kilometer funktioniert.","Choose one official stargazing site, inspect its return path before twilight and finish before transport or parking restrictions become uncertain.","Wähle einen offiziellen Stargazing-Ort, prüfe seinen Rückweg vor der Dämmerung und beende die Sitzung, bevor Transport- oder Parkregeln unsicher werden.","Use the smallest practical light, stay on paths and keep voices, vehicles and tripods away from homes and protected vegetation.","Nutze das kleinste praktikable Licht, bleibe auf Wegen und halte Stimmen, Fahrzeuge sowie Stative von Häusern und geschützter Vegetation fern.","If access is unclear, observe from the accommodation area rather than treating another rural car park as interchangeable.","Bei unklarem Zugang beobachte nahe der Unterkunft, statt einen anderen ländlichen Parkplatz als austauschbar zu behandeln."],
];

for (const row of additional) {
  const [id,name,countryCode,countryName,continent,regions,timezone,priority,tags,affiliateQuery,stay,sites,urls,titleEn,titleDe,openingEn,openingDe,constraintEn,constraintDe,routeEn,routeDe,conductEn,conductDe,fallbackEn,fallbackDe] = row;
  candidates.push({ id,name,countryCode,countryName,continent,regions,timezone,priority,tags,affiliateQuery,stay,sites,
    source: [["Official destination authority",`${name} astronomy guidance`,urls[0],"official-destination"],["Protected-area authority",`${name} access guidance`,urls[1],"protected-area"],["Public visitor authority",`${name} visitor information`,urls[2],"public-agency"]],
    title: bi(titleEn,titleDe), opening: bi(openingEn,openingDe), constraint: bi(constraintEn,constraintDe), route: bi(routeEn,routeDe), conduct: bi(conductEn,conductDe), fallback: bi(fallbackEn,fallbackDe) });
}

const finalCandidates = [
  ["kalbarri","Kalbarri","AU","Australia","oceania",["western-australia","oceania"],"Australia/Perth",86,["coast","outback","dark-sky","national-park"],"Kalbarri Western Australia",["kalbarri-town","Kalbarri",-27.711,114.165],[["kalbarri-skywalk-night","Kalbarri Skywalk",-27.823,114.473,150,"national-park-skywalk","limited",68,"https://www.kalbarri.org.au/see-do/kalbarri-skywalk"],["meanarra-hill-lookout","Meanarra Hill lookout",-27.694,114.174,190,"hilltop-lookout","limited",66,"https://exploreparks.dbca.wa.gov.au/site/meanarra-hill-lookout"]],["https://www.kalbarri.org.au/see-do/kalbarri-skywalk","https://exploreparks.dbca.wa.gov.au/park/kalbarri-national-park","https://www.emergency.wa.gov.au/"],"Kalbarri after sunset without treating the gorge as a night trail","Kalbarri nach Sonnenuntergang ohne die Schlucht zum Nachtweg zu machen","Kalbarri offers an unusually open western sky, but the national-park gorge remains a hot, remote environment. The Skywalk can support a carefully checked visit from its established platform. Meanarra Hill keeps the alternative closer to town.","Kalbarri bietet einen ungewöhnlich offenen Westhimmel, doch die Nationalparkschlucht bleibt heiß und abgelegen. Der Skywalk kann nach sorgfältiger Prüfung von seiner festen Plattform genutzt werden. Meanarra Hill hält die Alternative näher am Ort.","Heat, fire, road closures, unlit structures and the distance from help make current park and emergency notices essential.","Hitze, Feuer, Straßensperren, unbeleuchtete Anlagen und die Entfernung zu Hilfe machen aktuelle Park- und Notfallmeldungen unverzichtbar.","Visit the Skywalk in daylight first, return only if current access permits it and stay entirely on the built platform and car-park route.","Besuche den Skywalk zuerst bei Tageslicht, kehre nur bei aktuell erlaubtem Zugang zurück und bleibe vollständig auf Plattform und Parkplatzweg.","Do not enter gorge trails at night, feed wildlife or use bright lights across other visitors and the Murchison landscape.","Betrete nachts keine Schluchtwege, füttere keine Tiere und richte kein helles Licht auf Besucher oder die Murchison-Landschaft.","Any access doubt shifts the session to Meanarra or the town edge after a separate check, never to an unsigned gorge track.","Jeder Zugangszweifel verlagert die Sitzung nach separater Prüfung zu Meanarra oder an den Ortsrand, niemals auf einen unmarkierten Schluchtweg."],
  ["river-murray","River Murray","AU","Australia","oceania",["south-australia","oceania"],"Australia/Adelaide",85,["river","dark-sky","low-elevation","road-trip"],"River Murray Dark Sky Reserve South Australia",["mannum","Mannum",-34.912,139.313],[["big-bend-astro-pad","Big Bend astronomy pad",-34.633067,139.665983,45,"astronomy-pad","yes",82,"https://www.rivermurraydarkskyreserve.org/visit"],["towitta-astro-pad","Towitta astronomy pad",-34.524117,139.24845,105,"astronomy-pad","yes",80,"https://www.rivermurraydarkskyreserve.org/visit"]],["https://www.rivermurraydarkskyreserve.org/visit","https://www.rivermurraydarkskyreserve.org/","https://www.parks.sa.gov.au/know-before-you-go"],"One River Murray astro pad and no late river crossing","Ein River-Murray-Astro-Pad ohne späte Flussquerung","The River Murray reserve has an advantage many large dark-sky regions lack. Its published astronomy pads make the destination precise. Big Bend opens toward rural sky east of the river. Towitta suits a western approach; they should not become two stops in one tired night.","Das River-Murray-Reservat besitzt einen Vorteil, der vielen großen Dark-Sky-Regionen fehlt. Seine veröffentlichten Astronomie-Pads machen das Ziel präzise. Big Bend öffnet den ländlichen Himmel östlich des Flusses. Towitta passt zu einer westlichen Anfahrt. Beide gehören nicht in eine müde Nacht.","Ferry schedules, river fog, livestock, heat and long rural roads determine which side of the Murray should be chosen.","Fährzeiten, Flussnebel, Weidetiere, Hitze und lange Landstraßen bestimmen, welche Seite des Murray gewählt wird.","Select Big Bend or Towitta from the accommodation route, reach it before dusk and return without adding a ferry or cross-reserve detour.","Wähle Big Bend oder Towitta nach der Unterkunftsroute, erreiche den Ort vor der Dämmerung und kehre ohne Fähre oder Umweg durch das Reservat zurück.","Use the astronomy pad footprint, close gates, avoid crops and stock and keep vehicle lights pointed away from observers.","Nutze die Fläche des Astronomy Pads, schließe Tore, meide Felder und Tiere und richte Fahrzeuglicht von Beobachtern weg.","Fog or a missed ferry is solved by staying on the current riverbank, not by accelerating through unfamiliar rural roads.","Nebel oder eine verpasste Fähre werden durch Verbleib am aktuellen Ufer gelöst, nicht durch schnelleres Fahren auf unbekannten Landstraßen."],
  ["great-barrier-island","Aotea Great Barrier Island","NZ","New Zealand","oceania",["auckland-region","oceania"],"Pacific/Auckland",92,["island","dark-sky-sanctuary","coast","remote"],"Aotea Great Barrier Island New Zealand",["claris-aotea","Claris",-36.242,175.472],[["medlands-beach-night","Medlands Beach",-36.263,175.496,5,"beach","yes",76,"https://www.greatbarrier.co.nz/dark-sky-sanctuary/"],["windy-canyon-aotea","Windy Canyon trailhead",-36.199,175.447,210,"trailhead","limited",52,"https://www.doc.govt.nz/parks-and-recreation/places-to-go/auckland/places/great-barrier-island-aotea/"]],["https://www.greatbarrier.co.nz/dark-sky-sanctuary/","https://www.doc.govt.nz/parks-and-recreation/places-to-go/auckland/places/great-barrier-island-aotea/","https://www.aucklandcouncil.govt.nz/parks-recreation/Pages/default.aspx"],"Aotea from a beach you already know in daylight","Aotea von einem Strand, den du bei Tageslicht kennst","Aotea's sanctuary status describes island-wide darkness, not permission to enter every beach, track or property at night. Medlands is the simpler independent setting when tide, access and accommodation are nearby. Windy Canyon remains a daylight hiking route unless current local guidance explicitly supports the intended use.","Aoteas Sanctuary-Status beschreibt inselweite Dunkelheit und keine Erlaubnis, jeden Strand, Weg oder jedes Grundstück nachts zu betreten. Medlands ist einfacher, wenn Tide, Zugang und Unterkunft nahe liegen. Windy Canyon bleibt eine Tageswanderroute, solange aktuelle lokale Hinweise die geplante Nutzung nicht ausdrücklich tragen.","Ferry and flight disruption, tides, rough roads, limited services and conservation rules make the island plan dependent on preparation before arrival.","Fähr- und Flugausfälle, Tide, raue Straßen, begrenzte Services und Naturschutzregeln machen den Inselplan von Vorbereitung vor der Ankunft abhängig.","Stay near Claris or Medlands, inspect the beach access at low-risk daylight and keep the night session above the active tide line.","Übernachte nahe Claris oder Medlands, prüfe den Strandzugang bei sicherem Tageslicht und halte die Nachtsitzung oberhalb der aktiven Flutlinie.","Protect nesting birds, dunes and residents' privacy, carry all waste and use no open flame on the beach.","Schütze brütende Vögel, Dünen und die Privatsphäre der Bewohner, nimm allen Abfall mit und nutze kein offenes Feuer am Strand.","Bad marine weather means observing briefly near the booked accommodation, not attempting an unfamiliar island road or coastal track.","Schlechtes Seewetter bedeutet kurze Beobachtung nahe der Unterkunft statt einer unbekannten Inselstraße oder Küstenroute."],
  ["wairarapa","Wairarapa","NZ","New Zealand","oceania",["north-island","oceania"],"Pacific/Auckland",91,["dark-sky-reserve","farmland","southern-sky","accessible"],"Wairarapa New Zealand",["martinborough","Martinborough",-41.219,175.46],[["star-safari-wairarapa","Star Safari",-41.1425,175.5175,90,"private-observatory","limited",82,"https://star-safari.nz/"],["stonehenge-aotearoa-night","Stonehenge Aotearoa",-40.996,175.676,170,"astronomy-centre","limited",78,"https://stonehenge-aotearoa.nz/" ]],["https://wairarapadarksky.nz/","https://star-safari.nz/","https://stonehenge-aotearoa.nz/"],"A booked Wairarapa astronomy evening, not a farm-gate search","Ein gebuchter Astronomieabend in Wairarapa statt Suche am Farmtor","Wairarapa combines a certified reserve with working farms and two established visitor experiences. Star Safari provides a hosted small-group setting. Stonehenge Aotearoa offers a different cultural and astronomical programme. Neither turns surrounding private land into public observing space.","Wairarapa verbindet ein zertifiziertes Reservat mit aktiven Farmen und zwei etablierten Besuchserlebnissen. Star Safari bietet eine betreute Kleingruppe. Stonehenge Aotearoa folgt einem anderen kulturellen und astronomischen Programm. Keines macht umliegendes Privatland zur öffentlichen Beobachtungsfläche.","Booking status, rural road visibility, livestock and changeable North Island weather decide whether the evening can proceed.","Buchungsstatus, Sicht auf Landstraßen, Weidetiere und wechselhaftes Nordinselwetter entscheiden, ob der Abend stattfinden kann.","Choose one dated programme near Martinborough, arrive early enough to find the entrance and return directly after the host closes the session.","Wähle ein terminiertes Programm nahe Martinborough, komme früh genug für die Einfahrt und kehre nach Ende der Sitzung direkt zurück.","Respect hosts, gates, neighbours and farm biosecurity; do not stop on private verges to extend a paid session.","Respektiere Gastgeber, Tore, Nachbarn und Farm-Biosicherheit. Halte nicht auf privaten Seitenstreifen, um eine gebuchte Sitzung zu verlängern.","A weather cancellation becomes a local indoor evening or a new booking, not an unsupported attempt on another farm road.","Eine wetterbedingte Absage wird zu einem lokalen Innenabend oder neuer Buchung und nicht zu einem unbestätigten Versuch auf einer anderen Farmstraße."],
  ["kaikoura","Kaikōura","NZ","New Zealand","oceania",["south-island","oceania"],"Pacific/Auckland",88,["coast","dark-sky-sanctuary","mountains","southern-sky"],"Kaikoura New Zealand",["kaikoura-town","Kaikōura",-42.4,173.681],[["south-bay-kaikoura","South Bay recreation area",-42.429,173.681,8,"coastal-recreation-area","yes",74,"https://kaikouradarksky.nz/"],["point-kean-night-area","Point Kean car park",-42.423,173.71,5,"coastal-car-park","limited",64,"https://www.doc.govt.nz/parks-and-recreation/places-to-go/marlborough/places/kaikoura-area/" ]],["https://kaikouradarksky.nz/","https://www.doc.govt.nz/parks-and-recreation/places-to-go/marlborough/places/kaikoura-area/","https://www.kaikoura.govt.nz/our-district/dark-sky"],"Kaikōura between mountain weather and a live shoreline","Kaikōura zwischen Bergwetter und lebendiger Küste","Kaikōura's darkness is framed by mountains and ocean, which makes the horizon memorable and the shoreline dynamic. South Bay offers a broad established recreation area. Point Kean requires extra care around seals, tide, track limits and current parking rules.","Kaikōuras Dunkelheit wird von Bergen und Meer gerahmt. Das macht den Horizont eindrucksvoll und die Küste dynamisch. South Bay bietet eine breite etablierte Freizeitfläche. Point Kean verlangt besondere Vorsicht bei Robben, Tide, Weggrenzen und aktuellen Parkregeln.","Marine fog, strong wind, earthquake-related closures, wildlife and waves can alter access faster than a monthly climate score suggests.","Seenebel, starker Wind, erdbebenbedingte Sperren, Wildtiere und Wellen können den Zugang schneller verändern, als ein Monatswert vermuten lässt.","Use South Bay as the default, mark the vehicle and safe water boundary before twilight and avoid moving around the peninsula after dark.","Nutze South Bay als Standard, erkenne Fahrzeug und sichere Wassergrenze vor der Dämmerung und wechsle nachts nicht um die Halbinsel.","Give seals generous distance, stay out of nesting and tidal areas and keep the recreation route clear.","Halte großen Abstand zu Robben, bleibe aus Brut- und Gezeitenflächen und halte die Freizeitrouten frei.","Fog or high wind moves the evening back to town; the mountain side is not an automatic escape from coastal conditions.","Nebel oder starker Wind verlagern den Abend in den Ort. Die Bergseite ist kein automatischer Ausweg aus Küstenbedingungen."],
  ["oudtshoorn","Oudtshoorn","ZA","South Africa","africa",["western-cape","africa"],"Africa/Johannesburg",84,["semi-desert","southern-sky","private-reserve","dry"],"Oudtshoorn Klein Karoo South Africa",["oudtshoorn-town","Oudtshoorn",-33.59,22.202],[["buffelsdrift-night-experience","Buffelsdrift Game Lodge",-33.516,22.244,340,"private-reserve-lodge","limited",76,"https://www.buffelsdrift.com/activities/stargazing/"],["de-zeekoe-night-area","De Zeekoe farm stay",-33.66,22.196,310,"farm-stay","limited",68,"https://dezeekoe.co.za/"]],["https://www.buffelsdrift.com/activities/stargazing/","https://dezeekoe.co.za/","https://www.oudtshoorn.com/"],"Klein Karoo stars inside a booked property","Klein-Karoo-Sterne innerhalb eines gebuchten Grundstücks","Oudtshoorn's dry interior sky is attractive, but the most responsible night access is tied to a host. Buffelsdrift advertises a guided stargazing activity. De Zeekoe can support a quieter stay-based session only with direct permission for the exact area.","Oudtshoorns trockener Binnenhimmel ist attraktiv, doch der verantwortungsvollste Nachtzugang ist an einen Gastgeber gebunden. Buffelsdrift bietet eine geführte Stargazing-Aktivität an. De Zeekoe kann eine ruhigere, unterkunftsgebundene Sitzung nur mit direkter Erlaubnis für die genaue Fläche tragen.","Wildlife, private farm boundaries, gravel roads, summer heat and programme availability rule out casual roadside observation.","Wildtiere, private Farmgrenzen, Schotterstraßen, Sommerhitze und Programmverfügbarkeit schließen beiläufige Straßenrandbeobachtung aus.","Book the lodge or farm first, confirm the meeting point and keep the entire evening within the host's lit and unlit movement rules.","Buche Lodge oder Farm zuerst, bestätige den Treffpunkt und halte den ganzen Abend innerhalb der Bewegungs- und Lichtregeln des Gastgebers.","Follow every wildlife instruction, use no food or flash outside approved areas and never leave the property route alone at night.","Befolge alle Wildtierhinweise, nutze außerhalb erlaubter Flächen weder Essen noch Blitz und verlasse die Grundstücksroute nachts nie allein.","If the host cancels for weather or wildlife, remain at the accommodation and reschedule instead of searching farm roads.","Sagt der Gastgeber wegen Wetter oder Wildtieren ab, bleibe in der Unterkunft und buche neu, statt Farmstraßen abzusuchen."],
  ["headlands-michigan","Headlands","US","United States","north-america",["michigan","north-america"],"America/Detroit",82,["lake","dark-sky-park","accessible","forest"],"Headlands Dark Sky Park Michigan",["mackinaw-city","Mackinaw City",45.777,-84.727],[["headlands-waterfront-event-center","Headlands waterfront viewing area",45.779,-84.782,185,"dark-sky-park","yes",82,"https://www.midarkskypark.org/visit/"],["mcgulpin-point","McGulpin Point",45.787,-84.773,180,"lighthouse-grounds","limited",66,"https://www.mcgulpinpoint.org/" ]],["https://www.midarkskypark.org/visit/","https://www.midarkskypark.org/programs-events/","https://www.mcgulpinpoint.org/"],"A Headlands night that stays inside the county park","Eine Headlands-Nacht innerhalb des County Parks","Headlands is a purpose-built dark-sky destination near Mackinaw City, which removes the need to hunt for a Lake Michigan pull-out. Its waterfront viewing area is the default. McGulpin Point is a separate historic property whose hours and permissions must be checked independently.","Headlands ist ein eigens ausgewiesenes Dark-Sky-Ziel nahe Mackinaw City. Dadurch entfällt die Suche nach einer Haltebucht am Lake Michigan. Die Ufer-Beobachtungsfläche ist der Standard. McGulpin Point ist ein separates historisches Grundstück mit eigenen Zeiten und Erlaubnissen.","Lake weather, snow, shoreline ice, event crowds and parking instructions determine the practical visit.","Seewetter, Schnee, Ufervereisung, Veranstaltungsandrang und Parkhinweise bestimmen den praktischen Besuch.","Check the Headlands programme, arrive before the darkest period and remain on the county park's signed path between parking and water.","Prüfe das Headlands-Programm, komme vor der dunkelsten Phase und bleibe auf dem beschilderten Weg des County Parks zwischen Parkplatz und Wasser.","Keep the shoreline and event routes open, use no bright flash and respect all quiet and facility rules.","Halte Ufer und Veranstaltungswege frei, nutze keinen hellen Blitz und respektiere Ruhe- sowie Anlagenregeln.","Ice, wind or a full event should move the session back to Mackinaw City rather than to an unverified lakeshore.","Eis, Wind oder eine volle Veranstaltung verlagern die Sitzung nach Mackinaw City statt an ein unbestätigtes Seeufer."],
  ["wadi-rum","Wadi Rum","JO","Jordan","asia",["aqaba","asia"],"Asia/Amman",93,["desert","unesco","guided","remote"],"Wadi Rum Jordan",["wadi-rum-village","Wadi Rum Village",29.574,35.422],[["wadi-rum-visitor-centre","Wadi Rum Visitor Centre",29.64,35.434,930,"protected-area-gateway","limited",66,"https://wadirum.jo/"],["wadi-rum-booked-camp","Booked Wadi Rum desert camp",29.56,35.43,980,"desert-camp","limited",72,"https://international.visitjordan.com/Wheretogo/Wadi-Rum"]],["https://wadirum.jo/","https://international.visitjordan.com/Wheretogo/Wadi-Rum","https://whc.unesco.org/en/list/1377/"],"Wadi Rum astronomy from a booked camp, not an open map pin","Wadi-Rum-Astronomie vom gebuchten Camp statt von einem Kartenpunkt","Wadi Rum is a protected desert landscape where a map coordinate cannot replace a registered local arrangement. The visitor centre is the gateway, not the overnight observing field. A booked camp or guide should define transport, the exact place and the return.","Wadi Rum ist eine geschützte Wüstenlandschaft, in der ein Kartenpunkt keine registrierte lokale Regelung ersetzt. Das Besucherzentrum ist das Tor und nicht das nächtliche Beobachtungsfeld. Ein gebuchtes Camp oder ein Guide definiert Transport, genauen Ort und Rückkehr.","Heat, cold, sand, flash floods, navigation and protected-area rules make independent night driving unsuitable.","Hitze, Kälte, Sand, Sturzfluten, Navigation und Schutzgebietsregeln machen unabhängiges Nachtfahren ungeeignet.","Register at the visitor centre, meet the confirmed operator and observe only from the camp or stop selected for that itinerary.","Registriere dich am Besucherzentrum, triff den bestätigten Anbieter und beobachte nur vom Camp oder Stopp des gebuchten Plans.","Respect Bedouin hosts, archaeology and quiet; leave no waste and never drive or walk away from the agreed route.","Respektiere beduinische Gastgeber, Archäologie und Ruhe. Hinterlasse keinen Abfall und entferne dich nie fahrend oder gehend von der vereinbarten Route.","Wind, flood risk or a cancelled booking means staying in Wadi Rum Village or Aqaba, not hiring an informal night drive.","Wind, Sturzflutrisiko oder stornierte Buchung bedeuten Aufenthalt in Wadi Rum Village oder Aqaba und keine informelle Nachtfahrt."],
  ["jaisalmer","Jaisalmer","IN","India","asia",["rajasthan","asia"],"Asia/Kolkata",85,["desert","guided","culture","dry"],"Jaisalmer Thar Desert India",["jaisalmer-city","Jaisalmer",26.9157,70.9083],[["sam-sand-dunes-camp-zone","Sam Sand Dunes camp zone",26.838,70.536,225,"desert-tourism-zone","limited",66,"https://www.tourism.rajasthan.gov.in/jaisalmer.html"],["khuri-village-camp-zone","Khuri village camp zone",26.619,70.723,230,"desert-village","limited",64,"https://www.incredibleindia.gov.in/en/rajasthan/jaisalmer"]],["https://www.tourism.rajasthan.gov.in/jaisalmer.html","https://www.incredibleindia.gov.in/en/rajasthan/jaisalmer","https://jaisalmer.rajasthan.gov.in/"],"A Thar Desert night with transport agreed in advance","Eine Thar-Wüstennacht mit vorab geklärtem Transport","Jaisalmer's desert sky is inseparable from camp quality, transport and the chosen tourism zone. Sam is busy and easy to book. Khuri can feel quieter, but it still requires a confirmed host and vehicle rather than independent movement onto dunes.","Jaisalmers Wüstenhimmel ist untrennbar mit Campqualität, Transport und der gewählten Tourismuszone verbunden. Sam ist belebt und leicht buchbar. Khuri kann ruhiger wirken, verlangt aber ebenfalls einen bestätigten Gastgeber und ein Fahrzeug statt unabhängiger Bewegung auf Dünen.","Heat, cold, sand, traffic, informal sales and poorly specified camp locations can undermine both safety and darkness.","Hitze, Kälte, Sand, Verkehr, informeller Verkauf und ungenau beschriebene Camp-Lagen können Sicherheit und Dunkelheit beeinträchtigen.","Book a named camp with round-trip transport from Jaisalmer, confirm the exact dune zone and keep the observing period inside the hosted programme.","Buche ein benanntes Camp mit Hin- und Rücktransport ab Jaisalmer, bestätige die genaue Dünenzone und halte die Beobachtung innerhalb des betreuten Programms.","Avoid driving over vegetation, leave no plastic or food waste and respect village, livestock and cultural boundaries.","Fahre nicht über Vegetation, hinterlasse weder Plastik noch Essensreste und respektiere Dorf-, Tier- und Kulturgrenzen.","An unclear operator, dust storm or transport change is reason to remain in Jaisalmer and rebook through a traceable provider.","Ein unklarer Anbieter, Staubsturm oder Transportwechsel ist Grund, in Jaisalmer zu bleiben und bei einem nachvollziehbaren Anbieter neu zu buchen."],
  ["aenos","Mount Aenos","GR","Greece","europe",["ionian-islands","europe"],"Europe/Athens",82,["island","mountain","dark-sky-park","forest"],"Mount Aenos Kefalonia Greece",["sami-kefalonia","Sami, Kefalonia",38.25,20.646],[["aenos-entrance-view-area","Mount Aenos entrance viewing area",38.162,20.663,1120,"national-park-entrance","limited",68,"https://aenosnationalpark.gr/en/"],["aenos-picnic-area","Mount Aenos picnic area",38.189,20.63,930,"forest-picnic-area","limited",62,"https://aenosnationalpark.gr/en/activities/"]],["https://aenosnationalpark.gr/en/","https://aenosnationalpark.gr/en/activities/","https://darksky.org/places/aenos-dark-sky-park/"],"Mount Aenos with the forest road settled before dusk","Mount Aenos mit geklärter Waldstraße vor der Dämmerung","Mount Aenos brings a dark mountain into an island holiday, but the fir forest and park road require more discipline than a coastal viewpoint. The entrance area is the safer independent reference. Interior picnic areas depend on explicit current access.","Mount Aenos bringt einen dunklen Berg in einen Inselurlaub, doch Tannenwald und Parkstraße verlangen mehr Disziplin als ein Küstenaussichtspunkt. Der Eingangsbereich ist die sicherere unabhängige Referenz. Innere Picknickflächen hängen von ausdrücklich aktuellem Zugang ab.","Fire restrictions, wind, fog, road gates and forest navigation can close the useful night window even under clear coastal skies.","Feuerbeschränkungen, Wind, Nebel, Straßentore und Waldnavigation können das nutzbare Nachtfenster trotz klarer Küste schließen.","Check the park on the travel day, inspect the entrance area in daylight and descend on the same route before fatigue builds.","Prüfe den Park am Reisetag, erkunde den Eingangsbereich bei Tageslicht und fahre auf derselben Route ab, bevor Müdigkeit wächst.","Use no flame, protect the endemic fir forest, keep roads open and follow every seasonal fire instruction.","Nutze kein Feuer, schütze den endemischen Tannenwald, halte Straßen frei und befolge alle saisonalen Feuerhinweise.","A closed gate or rising wind redirects the evening to a legal coastal area near the accommodation, not deeper into the forest.","Ein geschlossenes Tor oder stärkerer Wind verlagert den Abend an eine legale Küstenfläche nahe der Unterkunft und nicht tiefer in den Wald."],
];

for (const row of finalCandidates) {
  const [id,name,countryCode,countryName,continent,regions,timezone,priority,tags,affiliateQuery,stay,sites,urls,titleEn,titleDe,openingEn,openingDe,constraintEn,constraintDe,routeEn,routeDe,conductEn,conductDe,fallbackEn,fallbackDe] = row;
  candidates.push({ id,name,countryCode,countryName,continent,regions,timezone,priority,tags,affiliateQuery,stay,sites,
    source: [["Official destination authority",`${name} destination guidance`,urls[0],"official-destination"],["Protected-area or visitor authority",`${name} access guidance`,urls[1],"protected-area"],["Public or nonprofit authority",`${name} status and context`,urls[2],"nonprofit-certifier"]],
    title: bi(titleEn,titleDe), opening: bi(openingEn,openingDe), constraint: bi(constraintEn,constraintDe), route: bi(routeEn,routeDe), conduct: bi(conductEn,conductDe), fallback: bi(fallbackEn,fallbackDe) });
}

if (candidates.length !== 25) throw new Error(`Catalog expansion requires 25 candidates, found ${candidates.length}`);

const sourceIds = (item) => [`${item.id}-place`, `${item.id}-access`, `${item.id}-status`];
const sourceRecords = (item) => item.source.map(([publisher, title, url, authority], index) => ({
  id: sourceIds(item)[index], publisher, title, url, checkedAt: "2026-08-31", authority,
}));

function guideFor(item, index) {
  const ids = sourceIds(item);
  const primary = item.sites[0][1];
  const secondary = item.sites[1][1];
  const stayName = item.stay[1];
  const openingTurn = [
    bi(`The practical value of ${item.name} appears when the chosen site, legal access and return journey are treated as one decision.`, `Der praktische Wert von ${item.name} zeigt sich, wenn gewählter Ort, legaler Zugang und Rückweg als eine Entscheidung behandelt werden.`),
    bi(`${item.name} is best understood through the final safe kilometre rather than through a regional darkness label alone.`, `${item.name} lässt sich am besten über den letzten sicheren Kilometer verstehen und nicht allein über ein regionales Dunkelheitslabel.`),
    bi(`A useful night in ${item.name} begins with a precise place and a credible way home.`, `Eine brauchbare Nacht in ${item.name} beginnt mit einem präzisen Ort und einem glaubwürdigen Heimweg.`),
    bi(`Darkness is only one part of the ${item.name} decision.`, `Dunkelheit ist nur ein Teil der Entscheidung für ${item.name}.`),
    bi(`${item.name} rewards restraint because the strongest plan usually uses one site well.`, `${item.name} belohnt Zurückhaltung, weil der stärkste Plan meist einen Ort gut nutzt.`),
  ][index % 5];
  const sectionHeadings = [
    bi(`${primary} sets the shape of the evening`, `${primary} bestimmt die Form des Abends`),
    bi(`The condition that can cancel ${item.name}`, `Die Bedingung, die ${item.name} absagen kann`),
    bi(`A return to ${stayName} without improvisation`, `Rückkehr nach ${stayName} ohne Improvisation`),
  ];
  const standfirst = {
    en: `${item.opening.en} ${openingTurn.en} ${item.constraint.en} The score helps compare months, but it is not tonight's forecast and it does not prove that a road, gate, programme or parking area is open. Check the cited authority again on the travel day.`,
    de: `${item.opening.de} ${openingTurn.de} ${item.constraint.de} Der Wert hilft beim Monatsvergleich, ist aber keine Vorhersage für heute Nacht und beweist weder offene Straße noch Tor, Programm oder Parkplatz. Prüfe die zitierte Stelle am Reisetag erneut.`,
  };
  const editorialAngle = {
    en: `${item.route.en} That concrete route gives ${item.name} more value than a list of scenic pins. ${item.fallback.en}`,
    de: `${item.route.de} Diese konkrete Route gibt ${item.name} mehr Wert als eine Liste schöner Kartenpunkte. ${item.fallback.de}`,
  };
  const sections = [
    {
      id: `${item.id}-place-choice`, heading: sectionHeadings[0], sourceIds: ids,
      paragraphs: {
        en: [
          `${item.opening.en} ${primary} is the recommended site because its role can be explained from published visitor information rather than guessed from satellite imagery. ${secondary} remains a genuine alternative, yet its separate access conditions should be checked before leaving ${stayName}. Treat the two cards on the page as different plans. They are not an invitation to switch sites after dark whenever the first horizon disappoints.`,
          `${openingTurn.en} The useful comparison is therefore practical. Ask whether the car can remain legally, whether the last walking line is obvious, whether the site is compatible with current notices and whether a tired return still feels simple. The astronomical model changes with the selected coordinates, local time and elevation. It does not include cloud, smoke, terrain hidden from the dataset, buildings or temporary closures.`,
        ],
        de: [
          `${item.opening.de} ${primary} ist die Empfehlung, weil seine Rolle aus veröffentlichten Besucherinformationen erklärt werden kann und nicht aus Satellitenbildern geraten wird. ${secondary} bleibt eine echte Alternative, doch seine eigenen Zugangsbedingungen werden vor der Abfahrt aus ${stayName} geprüft. Die beiden Karten auf der Seite stehen für unterschiedliche Pläne und laden nicht dazu ein, nachts wegen eines enttäuschenden Horizonts zu wechseln.`,
          `${openingTurn.de} Der brauchbare Vergleich ist deshalb praktisch. Frage, ob das Auto legal stehen darf, ob der letzte Gehweg eindeutig ist, ob der Ort zu aktuellen Meldungen passt und ob eine müde Rückkehr einfach bleibt. Das astronomische Modell ändert sich mit gewählter Koordinate, Ortszeit und Höhe. Es enthält weder Wolken noch Rauch, verborgene Geländekanten, Gebäude oder temporäre Sperren.`,
        ],
      },
    },
    {
      id: `${item.id}-limiting-condition`, heading: sectionHeadings[1], sourceIds: ids,
      paragraphs: {
        en: [
          `${item.constraint.en} This is the part of the plan that deserves a fresh source check, even when the climatological month ranks well. Read alerts, operating hours, fire or wildlife notices and local weather together. A high score never compensates for an access restriction, unsafe surface or return that depends on reception and an untested road.`,
          `${item.name}'s best-month signal uses historical conditions to identify a useful season. For the actual evening, compare current cloud, wind, temperature, precipitation, smoke where relevant and Moon position. Cancel early when those inputs point in the same poor direction. Waiting at ${stayName} costs less than recovering from a bad late decision at ${primary}.`,
        ],
        de: [
          `${item.constraint.de} Dieser Teil des Plans verdient eine neue Quellenprüfung, selbst wenn der klimatologische Monat gut abschneidet. Lies Meldungen, Betriebszeiten, Feuer- oder Wildtierhinweise und lokales Wetter gemeinsam. Ein hoher Wert gleicht weder eine Zugangsbeschränkung noch unsicheren Untergrund oder eine Rückfahrt aus, die von Empfang und ungetesteter Straße abhängt.`,
          `Das Signal für den besten Monat in ${item.name} nutzt historische Bedingungen, um eine brauchbare Saison zu erkennen. Für den tatsächlichen Abend vergleichst du aktuelle Wolken, Wind, Temperatur, Niederschlag, gegebenenfalls Rauch und die Mondposition. Sage früh ab, wenn diese Eingaben gemeinsam gegen den Plan sprechen. Warten in ${stayName} kostet weniger als die Folgen einer schlechten späten Entscheidung an ${primary}.`,
        ],
      },
    },
    {
      id: `${item.id}-field-rhythm`, heading: sectionHeadings[2], sourceIds: ids,
      paragraphs: {
        en: [
          `${item.route.en} Arrive while signs, edges and the walking surface remain visible. Mark the vehicle, the safe observation footprint and the simplest retreat before opening equipment. A useful session can be short. Dark adaptation and patient naked-eye orientation often reveal more than hurried setup followed by a second drive.`,
          `${item.conduct.en} Pack in a fixed order, count every small item and leave while concentration is still good. ${item.fallback.en} That fallback is part of the route rather than a consolation prize. It protects the destination, the people sharing it and the credibility of a guide that must work beyond a perfect-weather photograph.`,
        ],
        de: [
          `${item.route.de} Komme an, solange Schilder, Kanten und Gehfläche sichtbar bleiben. Merke dir Fahrzeug, sichere Beobachtungsfläche und einfachsten Rückzug, bevor du Ausrüstung öffnest. Eine brauchbare Sitzung darf kurz sein. Dunkeladaption und ruhige Orientierung mit bloßem Auge zeigen oft mehr als hektischer Aufbau mit anschließender zweiter Fahrt.`,
          `${item.conduct.de} Packe in fester Reihenfolge, zähle jedes Kleinteil und fahre, solange die Konzentration gut ist. ${item.fallback.de} Diese Alternative ist Teil der Route und kein Trostpreis. Sie schützt das Ziel, die Menschen dort und die Glaubwürdigkeit eines Guides, der mehr leisten muss als ein Foto bei perfektem Wetter.`,
        ],
      },
    },
  ];
  const stepSpecs = [
    ["proof", bi(`Before leaving ${stayName}`, `Vor der Abfahrt aus ${stayName}`), bi("Confirm the exact access", "Den genauen Zugang bestätigen")],
    ["arrival", bi("While the ground is visible", "Solange der Boden sichtbar ist"), bi(`Read ${primary} in daylight`, `${primary} bei Tageslicht lesen`)],
    ["observe", bi("After full dark", "Nach vollständiger Dunkelheit"), bi("Keep the session inside one footprint", "Die Sitzung auf eine Fläche begrenzen")],
    ["return", bi("Before attention fades", "Bevor die Aufmerksamkeit nachlässt"), bi(`Return directly to ${stayName}`, `Direkt nach ${stayName} zurückkehren`)],
  ];
  const stepBodies = [
    bi(`${item.name} requires a same-day source check. Open all three cited authorities and confirm the status of ${primary}, the route, parking or booking, operating limits and current hazard notices. Save the result and directions offline. If the official information no longer supports the plan, use the stated fallback instead of treating an old page or map pin as permission.`, `${item.name} verlangt eine Quellenprüfung am selben Tag. Öffne alle drei zitierten Stellen und bestätige Status von ${primary}, Route, Parken oder Buchung, Betriebsgrenzen und aktuelle Gefahrenmeldungen. Speichere Ergebnis und Navigation offline. Tragen die offiziellen Informationen den Plan nicht mehr, nutze die genannte Alternative, statt eine alte Seite oder Kartenmarke als Erlaubnis zu verstehen.`),
    bi(`Reach ${primary} early enough to see every boundary that matters. Identify the legal vehicle position, safe walking line, observation surface and quickest retreat. Check wind, temperature and cloud once more before unpacking. Do not extend the route toward ${secondary} merely because time remains.`, `Erreiche ${primary} früh genug, um jede wichtige Grenze zu sehen. Bestimme legalen Fahrzeugplatz, sicheren Gehweg, Beobachtungsfläche und schnellsten Rückzug. Prüfe Wind, Temperatur und Wolken erneut, bevor du auspackst. Verlängere die Route nicht Richtung ${secondary}, nur weil noch Zeit bleibt.`),
    bi(`At ${primary}, let your eyes adapt before deciding what equipment is useful. Keep screens dim, point every lamp down and place bags and tripod legs outside shared movement lines. ${item.conduct.en} The site remains a real place with neighbours, wildlife or protected ground even when the sky becomes the main subject.`, `An ${primary} lässt du die Augen adaptieren, bevor du über Ausrüstung entscheidest. Dimme Bildschirme, richte jedes Licht nach unten und halte Taschen sowie Stativbeine aus gemeinsamen Wegen. ${item.conduct.de} Der Ort bleibt auch dann ein realer Platz mit Nachbarn, Wildtieren oder Schutzflächen, wenn der Himmel zum Hauptmotiv wird.`),
    bi(`Leave ${primary} with enough energy for a slow, predictable return. Pack completely, inspect the ground and use the route already learned in daylight. ${item.fallback.en} Record any access difference for the next visit rather than trying to solve it through a late detour.`, `Verlasse ${primary} mit genug Energie für eine langsame, vorhersehbare Rückkehr. Packe vollständig, prüfe den Boden und nutze die bei Tageslicht gelernte Route. ${item.fallback.de} Notiere Zugangsabweichungen für den nächsten Besuch, statt sie durch einen späten Umweg lösen zu wollen.`),
  ];
  return {
    version: 1, destinationId: item.id, slug: item.id,
    seoTitle: bi(`${item.name} stargazing guide: ${primary}`, `Stargazing-Guide ${item.name}: ${primary}`),
    seoDescription: bi(`Plan a responsible ${item.name} stargazing night at ${primary} with sourced access, current-condition checks and a clear return to ${stayName}.`, `Plane eine verantwortungsvolle Nacht in ${item.name} an ${primary} mit belegtem Zugang, aktueller Prüfung und klarer Rückkehr.`),
    standfirst, editorialAngle, sections,
    tour: {
      title: item.title,
      summary: bi(`${item.route.en} ${item.constraint.en} The route keeps the decision close to ${primary}, with ${stayName} as the known base and ${secondary} reserved for a separately verified plan.`, `${item.route.de} ${item.constraint.de} Die Route hält die Entscheidung nahe ${primary}, mit ${stayName} als bekannter Basis und ${secondary} nur für einen separat geprüften Plan.`),
      duration: bi("One evening with a daylight arrival and direct return", "Ein Abend mit Ankunft bei Tageslicht und direkter Rückkehr"),
      suitability: bi(`For independent visitors who can verify access, weather and the return route before reaching ${primary}; not for improvised night exploration.`, `Für unabhängige Besucher, die Zugang, Wetter und Rückweg vor der Ankunft an ${primary} prüfen können; nicht für spontane Nachterkundung.`),
      sourceIds: ids,
      steps: stepSpecs.map(([suffix,timeHint,title], stepIndex) => ({ id: `${item.id}-${suffix}`, timeHint, title, body: stepBodies[stepIndex], sourceIds: ids })),
    },
    fieldNotesTitle: bi(`Three decisions for ${item.name}`, `Drei Entscheidungen für ${item.name}`),
    fieldNotes: [
      { id: `${item.id}-access-note`, title: bi("Access evidence", "Zugangsnachweis"), body: bi(`${primary} remains usable only while the current authority supports the route described here. Check the dated notice, booking or operating rule and keep it offline. The coordinate positions the sky simulation; it does not grant entry or overnight use.`, `${primary} bleibt nur nutzbar, solange die aktuelle Behörde die hier beschriebene Route trägt. Prüfe datierte Meldung, Buchung oder Betriebsregel und speichere sie offline. Die Koordinate positioniert die Himmelssimulation und gewährt weder Zutritt noch Übernachtung.`), sourceIds: ids },
      { id: `${item.id}-weather-note`, title: bi("The real-night veto", "Das Veto der echten Nacht"), body: bi(`${item.constraint.en} Compare the live forecast and alerts with the historical month ranking. If visibility, surface or return safety is doubtful, the decision is to postpone even when the astronomy panel shows a favourable geometric sky.`, `${item.constraint.de} Vergleiche Live-Vorhersage und Meldungen mit der historischen Monatsrangliste. Sind Sicht, Untergrund oder Rückkehr unsicher, wird verschoben, selbst wenn das Astronomiepanel einen günstigen geometrischen Himmel zeigt.`), sourceIds: ids },
      { id: `${item.id}-fallback-note`, title: bi(`The ${stayName} fallback`, `Die Alternative ${stayName}`), body: bi(`${item.fallback.en} A fallback decided before sunset prevents unsafe bargaining with conditions later. It also keeps private land, protected habitat and quiet local roads from becoming substitutes for a closed or unsuitable official site.`, `${item.fallback.de} Eine vor Sonnenuntergang gewählte Alternative verhindert späteres riskantes Verhandeln mit den Bedingungen. Sie schützt außerdem Privatland, Lebensräume und ruhige lokale Straßen davor, Ersatz für einen geschlossenen oder ungeeigneten offiziellen Ort zu werden.`), sourceIds: ids },
    ],
    faq: [
      { question: bi(`Is ${primary} open every night?`, `Ist ${primary} jede Nacht geöffnet?`), answer: bi(`${primary} has no permanent access guarantee. Use the cited authority to check the actual date, including gates, programmes, parking, seasonal limits and emergency notices. ${item.route.en} If a rule is unclear, contact the operator or protected-area authority before travel rather than interpreting silence as permission.`, `Für ${primary} gibt es keine dauerhafte Zugangsgarantie. Prüfe das tatsächliche Datum bei der zitierten Stelle, einschließlich Toren, Programmen, Parken, Saisonlimits und Notfallmeldungen. ${item.route.de} Ist eine Regel unklar, kontaktiere Betreiber oder Schutzgebietsverwaltung vor der Reise und deute Schweigen nicht als Erlaubnis.`), sourceIds: ids },
      { question: bi(`Does the ${item.name} score predict tonight's sky?`, `Sagt der ${item.name}-Wert den Himmel heute Nacht voraus?`), answer: bi(`${item.name}'s monthly score summarises historical climate, darkness, elevation and access inputs. The astronomical panel calculates Sun, Moon and star geometry for the selected site and time. Neither replaces a live cloud, wind, smoke, road or safety check. ${item.constraint.en}`, `Der Monatswert für ${item.name} fasst historische Klima-, Dunkelheits-, Höhen- und Zugangsdaten zusammen. Das Astronomiepanel berechnet Sonne, Mond und Sterngeometrie für Ort und Zeit. Beides ersetzt keine Live-Prüfung von Wolken, Wind, Rauch, Straße oder Sicherheit. ${item.constraint.de}`), sourceIds: ids },
    ],
    sources: sourceRecords(item), lastReviewedAt: "2026-08-31",
  };
}

function tourFor(item, index) {
  const ids = sourceIds(item);
  const primary = item.sites[0][1];
  const secondary = item.sites[1][1];
  const stayName = item.stay[1];
  const orders = [
    ["decisions", "prose", "schedule", "note"],
    ["prose", "schedule", "decisions", "note"],
    ["schedule", "note", "prose", "decisions"],
    ["note", "decisions", "schedule", "prose"],
  ];
  const blocks = {
    prose: { id: `${item.id}-tour-ground`, kind: "prose", heading: bi(`Why ${primary} is enough for one night`, `Warum ${primary} für eine Nacht genügt`), paragraphs: {
      en: [`${item.opening.en} This tour commits to ${primary} because a single known site preserves attention for the sky and the return. ${secondary} is useful information for another date, not a target to add after darkness.`, `${item.conduct.en} Spend the first unlit minutes identifying cardinal directions and the broadest open horizon. Equipment should serve that observation rather than turning the evening into a complicated setup exercise.`],
      de: [`${item.opening.de} Diese Tour legt sich auf ${primary} fest, weil ein bekannter Ort Aufmerksamkeit für Himmel und Rückweg erhält. ${secondary} ist nützliche Information für ein anderes Datum und kein Ziel, das nach Einbruch der Dunkelheit ergänzt wird.`, `${item.conduct.de} Nutze die ersten unbeleuchteten Minuten für Himmelsrichtungen und den offensten Horizont. Ausrüstung dient dieser Beobachtung, statt den Abend in eine komplizierte Aufbauübung zu verwandeln.`],
    }, sourceIds: ids },
    note: { id: `${item.id}-tour-veto`, kind: "note", heading: bi(`What cancels the ${item.name} route`, `Was die Route in ${item.name} absagt`), body: bi(`${item.constraint.en} Treat that limit as a decision made before equipment leaves the vehicle. ${item.fallback.en} A shorter evening is a successful outcome when it prevents an exposed or unsupported return.`, `${item.constraint.de} Behandle diese Grenze als Entscheidung, bevor Ausrüstung das Fahrzeug verlässt. ${item.fallback.de} Ein kürzerer Abend ist erfolgreich, wenn er eine exponierte oder ungesicherte Rückkehr verhindert.`), sourceIds: ids, tone: "warning" },
    decisions: { id: `${item.id}-tour-choices`, kind: "decisions", heading: bi(`Two choices before leaving ${stayName}`, `Zwei Entscheidungen vor der Abfahrt aus ${stayName}`), introduction: bi("The route works only when access and conditions agree.", "Die Route funktioniert nur, wenn Zugang und Bedingungen übereinstimmen."), items: [
      { label: bi(`${primary} is confirmed`, `${primary} ist bestätigt`), body: bi(`For ${primary}, use the published route, arrive in daylight and keep the session at the selected site. Save the source and return directions offline so poor reception cannot change the agreed boundary.`, `Für ${primary} nutzt du die veröffentlichte Route, kommst bei Tageslicht und bleibst am gewählten Ort. Speichere Quelle und Rückweg offline, damit schlechter Empfang die vereinbarte Grenze nicht verändert.`), sourceIds: ids },
      { label: bi("Any essential detail is uncertain", "Ein wesentliches Detail ist unsicher"), body: bi(`${item.fallback.en} Do not substitute ${secondary} unless its own authority, route and timing have been checked before departure.`, `${item.fallback.de} Ersetze den Ort nicht durch ${secondary}, solange dessen eigene Behörde, Route und Zeit nicht vor der Abfahrt geprüft wurden.`), sourceIds: ids },
    ] },
    schedule: { id: `${item.id}-tour-timing`, kind: "schedule", heading: bi(`The evening rhythm at ${primary}`, `Der Abendrhythmus an ${primary}`), introduction: bi("Timing is built around visibility on arrival and attention on return.", "Die Zeitplanung richtet sich nach Sicht bei Ankunft und Aufmerksamkeit bei Rückkehr."), items: [
      { time: bi("Before sunset", "Vor Sonnenuntergang"), title: bi("Learn the last kilometre", "Den letzten Kilometer lernen"), body: bi(`Travel from ${stayName}, inspect the legal parking position, safe observation area and retreat while all surfaces are visible. Recheck current conditions before committing to the session.`, `Fahre aus ${stayName}, prüfe legalen Parkplatz, sichere Beobachtungsfläche und Rückzug, solange alle Flächen sichtbar sind. Prüfe aktuelle Bedingungen erneut, bevor du dich auf die Sitzung festlegst.`), sourceIds: ids },
      { time: bi("After darkness", "Nach Einbruch der Dunkelheit"), title: bi("Observe before adding equipment", "Vor zusätzlicher Ausrüstung beobachten"), body: bi(`At ${primary}, allow full dark adaptation, orient with the naked eye and add only equipment that can be managed without obstructing anyone. Keep the setup inside the footprint inspected earlier.`, `An ${primary} lässt du die Augen vollständig adaptieren, orientierst dich mit bloßem Auge und ergänzt nur Ausrüstung, die ohne Behinderung anderer nutzbar ist. Halte den Aufbau innerhalb der zuvor geprüften Fläche.`), sourceIds: ids },
      { time: bi("At the planned stop time", "Zur geplanten Endzeit"), title: bi("Leave on the known route", "Auf der bekannten Route fahren"), body: bi(`Leave ${primary} systematically, inspect the ground and return directly to ${stayName}. Do not trade a safe finish for a late move toward ${secondary} or an unverified roadside horizon.`, `Verlasse ${primary} systematisch, prüfe den Boden und kehre direkt nach ${stayName} zurück. Tausche ein sicheres Ende nicht gegen einen späten Wechsel zu ${secondary} oder einen unbestätigten Straßenhorizont.`), sourceIds: ids },
    ] },
  };
  return {
    version: 1, id: `${item.id}-one-site-night`, slug: `${item.id}-one-site-night`, destinationId: item.id, recommendedSiteId: item.sites[0][0],
    title: item.title,
    seoDescription: bi(`Follow a sourced one-site stargazing route from ${stayName} to ${primary}, with daylight arrival, current-condition checks and a direct return.`, `Folge einer belegten Ein-Ort-Stargazing-Route von ${stayName} zu ${primary}, mit Tageslicht-Ankunft, aktueller Prüfung und direkter Rückkehr.`),
    standfirst: bi(`${item.route.en} This self-guided route uses ${primary} as the fixed site and ${stayName} as the return base. ${item.constraint.en} The plan therefore values a verified entrance, an early arrival and an uneventful journey home more than an extra stop.`, `${item.route.de} Diese selbst geführte Route nutzt ${primary} als festen Ort und ${stayName} als Rückkehrbasis. ${item.constraint.de} Der Plan bewertet deshalb bestätigten Zugang, frühe Ankunft und eine ereignislose Heimfahrt höher als einen zusätzlichen Stopp.`),
    facts: [
      { label: bi("Chosen site", "Gewählter Ort"), value: bi(primary, primary), sourceIds: ids },
      { label: bi("Base", "Basis"), value: bi(stayName, stayName), sourceIds: ids },
      { label: bi("Arrival", "Ankunft"), value: bi("Before sunset, after a same-day access check", "Vor Sonnenuntergang nach Zugangskontrolle am selben Tag"), sourceIds: ids },
      { label: bi("Alternative", "Alternative"), value: bi(`${secondary}, only as a separately verified plan`, `${secondary}, nur als separat geprüfter Plan`), sourceIds: ids },
    ],
    blocks: orders[index % orders.length].map((kind) => blocks[kind]), sourceIds: ids, lastReviewedAt: "2026-08-31",
  };
}

const destinations = read("data-config/sources/destinations.json");
const sites = read("data-config/sources/observation-sites.json");
const stays = read("data-config/sources/stay-areas.json");
const destinationImages = read("data-config/sources/destination-images.json");
const siteImages = read("data-config/sources/site-images.json");
const guides = read("data-config/editorial/destination-guides.json");
const tours = read("data-config/editorial/location-tours.json");

const append = (array, item, key = "id") => {
  const index = array.findIndex((existing) => existing[key] === item[key]);
  if (index === -1) array.push(item);
  else array[index] = item;
};

for (const [index, item] of candidates.entries()) {
  const observationSiteIds = item.sites.map((site) => site[0]);
  append(destinations, { id: item.id, slug: item.id, name: item.name, countryCode: item.countryCode, countryName: item.countryName, continent: item.continent, regionSlugs: item.regions, timezone: item.timezone, active: true, priority: item.priority, tags: item.tags, observationSiteIds, stayAreaIds: [item.stay[0]], affiliateQuery: item.affiliateQuery });
  for (const site of item.sites) {
    const [id,name,lat,lon,elevationM,siteType,publicAccess,accessScore,notesSourceUrl] = site;
    append(sites, { id, slug: id, destinationId: item.id, name, lat, lon, elevationM, siteType, publicAccess, accessScore, active: true, priority: item.priority, certificationIds: [], notesSourceUrl,
      accessNotes: bi(`Use only the published visitor arrangement for ${name}. Confirm current access, parking or booking, hours and hazard notices before travel; the coordinate is not permission to enter or camp.`, `Nutze nur die veröffentlichte Besucherregelung für ${name}. Bestätige aktuellen Zugang, Parken oder Buchung, Zeiten und Gefahrenmeldungen vor der Reise; die Koordinate ist keine Zutritts- oder Campingerlaubnis.`) });
    append(siteImages, { slug: id, status: "pending", overrideReason: "Awaiting a fully attributed CC0, CC BY, CC BY-SA, public-domain, or government-work image." }, "slug");
  }
  append(stays, { id: item.stay[0], destinationId: item.id, name: item.stay[1], lat: item.stay[2], lon: item.stay[3], affiliateQuery: `${item.stay[1]} ${item.countryName}`, observationSiteIds });
  append(destinationImages, { slug: item.id, status: "pending", overrideReason: "Awaiting a fully attributed CC0, CC BY, CC BY-SA, public-domain, or government-work image." }, "slug");
  append(guides, guideFor(item, index), "slug");
  append(tours, tourFor(item, index), "slug");
}

write("data-config/sources/destinations.json", destinations);
write("data-config/sources/observation-sites.json", sites);
write("data-config/sources/stay-areas.json", stays);
write("data-config/sources/destination-images.json", destinationImages);
write("data-config/sources/site-images.json", siteImages);
write("data-config/editorial/destination-guides.json", guides);
write("data-config/editorial/location-tours.json", tours);

console.log(`Expanded catalog to ${destinations.length} destinations, ${sites.length} sites, ${guides.length} guides and ${tours.length} tours.`);

export { candidates, bi, read, write, root };
