import type { ConstellationCopy } from "./types";

const reviewedAt = "2026-08-27";
const factSources = [
  "https://www.iau.org/public/themes/constellations/",
  "https://github.com/Stellarium/stellarium-skycultures/tree/014fbb5e59233d133c22f9811af96b67d05a95c9/western",
];

export const constellationCopy: readonly ConstellationCopy[] = [
  { id: "andromeda", name: { de: "Andromeda", en: "Andromeda" }, recognitionHint: { de: "Suche eine lange, sanft gebogene Sternkette am Pegasus-Quadrat.", en: "Look for a long, gently curving chain extending from the Great Square of Pegasus." }, shortDescription: { de: "Eine nördliche Figur zwischen Pegasus und Perseus.", en: "A northern figure between Pegasus and Perseus." }, factSources, lastReviewedAt: reviewedAt },
  { id: "aquila", name: { de: "Adler", en: "Aquila" }, recognitionHint: { de: "Altair bildet mit zwei nahen Sternen eine markante kurze Linie.", en: "Altair forms a distinctive short line with two nearby stars." }, shortDescription: { de: "Der Adler liegt am Band der Milchstraße.", en: "The Eagle lies along the band of the Milky Way." }, factSources, lastReviewedAt: reviewedAt },
  { id: "carina", name: { de: "Kiel des Schiffs", en: "Carina" }, recognitionHint: { de: "Canopus markiert die helle Südspitze einer weit ausgreifenden Figur.", en: "Canopus marks the bright southern end of a broad figure." }, shortDescription: { de: "Ein südliches Sternbild des historischen Schiffs Argo.", en: "A southern constellation from the historic ship Argo." }, factSources, lastReviewedAt: reviewedAt },
  { id: "cassiopeia", name: { de: "Kassiopeia", en: "Cassiopeia" }, recognitionHint: { de: "Fünf helle Sterne bilden ein auffälliges W oder M.", en: "Five bright stars form a conspicuous W or M." }, shortDescription: { de: "Die zirkumpolare Figur steht nahe dem nördlichen Himmelspol.", en: "This circumpolar figure lies near the north celestial pole." }, factSources, lastReviewedAt: reviewedAt },
  { id: "centaurus", name: { de: "Zentaur", en: "Centaurus" }, recognitionHint: { de: "Alpha und Beta Centauri sind das helle Zeigerpaar nahe dem Kreuz des Südens.", en: "Alpha and Beta Centauri are the bright pointer pair near the Southern Cross." }, shortDescription: { de: "Eine große südliche Figur rund um einige der hellsten Sterne des Himmels.", en: "A large southern figure containing some of the sky's brightest stars." }, factSources, lastReviewedAt: reviewedAt },
  { id: "canis-major", name: { de: "Großer Hund", en: "Canis Major" }, recognitionHint: { de: "Beginne beim sehr hellen Sirius und folge der kompakten Figur darunter.", en: "Start at brilliant Sirius and follow the compact figure below it." }, shortDescription: { de: "Der Große Hund begleitet Orion am Winterhimmel.", en: "The Great Dog follows Orion across the winter sky." }, factSources, lastReviewedAt: reviewedAt },
  { id: "crux", name: { de: "Kreuz des Südens", en: "Crux" }, recognitionHint: { de: "Vier helle Sterne bilden ein kleines, deutliches Kreuz.", en: "Four bright stars form a small, distinct cross." }, shortDescription: { de: "Die kompakte Südfigur dient als Wegweiser zum südlichen Himmelspol.", en: "This compact southern figure helps point toward the south celestial pole." }, factSources, lastReviewedAt: reviewedAt },
  { id: "cygnus", name: { de: "Schwan", en: "Cygnus" }, recognitionHint: { de: "Deneb steht an einem Ende des großen Kreuzes in der Milchstraße.", en: "Deneb sits at one end of the large cross within the Milky Way." }, shortDescription: { de: "Der Schwan wird auch als Nördliches Kreuz erkannt.", en: "The Swan is also recognized as the Northern Cross." }, factSources, lastReviewedAt: reviewedAt },
  { id: "gemini", name: { de: "Zwillinge", en: "Gemini" }, recognitionHint: { de: "Castor und Pollux bilden ein helles, nahes Paar über zwei parallelen Sternreihen.", en: "Castor and Pollux form a bright pair above two roughly parallel star rows." }, shortDescription: { de: "Die Zwillinge liegen nördlich von Orion an der Ekliptik.", en: "The Twins lie north of Orion along the ecliptic." }, factSources, lastReviewedAt: reviewedAt },
  { id: "leo", name: { de: "Löwe", en: "Leo" }, recognitionHint: { de: "Eine sichelförmige Sternkette beginnt am hellen Regulus.", en: "A sickle-shaped chain of stars begins at bright Regulus." }, shortDescription: { de: "Der Löwe ist eine markante Frühlingsfigur entlang der Ekliptik.", en: "Leo is a prominent spring figure along the ecliptic." }, factSources, lastReviewedAt: reviewedAt },
  { id: "lyra", name: { de: "Leier", en: "Lyra" }, recognitionHint: { de: "Die sehr helle Wega sitzt neben einem kleinen Parallelogramm.", en: "Brilliant Vega sits beside a small parallelogram." }, shortDescription: { de: "Eine kleine nördliche Figur am Rand der Milchstraße.", en: "A small northern figure beside the Milky Way." }, factSources, lastReviewedAt: reviewedAt },
  { id: "orion", name: { de: "Orion", en: "Orion" }, recognitionHint: { de: "Drei fast gleich helle Sterne bilden den geraden Gürtel.", en: "Three similarly bright stars form the straight Belt." }, shortDescription: { de: "Die auffällige Äquatorfigur ist von beiden Hemisphären gut zu sehen.", en: "This prominent equatorial figure is visible from both hemispheres." }, factSources, lastReviewedAt: reviewedAt },
  { id: "pegasus", name: { de: "Pegasus", en: "Pegasus" }, recognitionHint: { de: "Vier Sterne bilden das große, nahezu leere Pegasus-Quadrat.", en: "Four stars outline the large, relatively empty Great Square of Pegasus." }, shortDescription: { de: "Das geflügelte Pferd prägt den nördlichen Herbsthimmel.", en: "The Winged Horse is a landmark of the northern autumn sky." }, factSources, lastReviewedAt: reviewedAt },
  { id: "scorpius", name: { de: "Skorpion", en: "Scorpius" }, recognitionHint: { de: "Vom rötlichen Antares windet sich eine lange Hakenform zum Stachel.", en: "A long hooked chain curls from reddish Antares toward the stinger." }, shortDescription: { de: "Der Skorpion liegt in einer sternreichen Region der Milchstraße.", en: "Scorpius lies in a star-rich region of the Milky Way." }, factSources, lastReviewedAt: reviewedAt },
  { id: "sagittarius", name: { de: "Schütze", en: "Sagittarius" }, recognitionHint: { de: "Eine kompakte Teekannenform zeigt in Richtung Milchstraßenzentrum.", en: "A compact Teapot shape points toward the Milky Way's center." }, shortDescription: { de: "Der Schütze steht vor besonders dichten Feldern der Milchstraße.", en: "Sagittarius sits against especially dense Milky Way star fields." }, factSources, lastReviewedAt: reviewedAt },
  { id: "taurus", name: { de: "Stier", en: "Taurus" }, recognitionHint: { de: "Aldebaran markiert ein V-förmiges Gesicht nahe den Plejaden.", en: "Aldebaran marks a V-shaped face near the Pleiades." }, shortDescription: { de: "Der Stier ist eine auffällige Winterfigur an der Ekliptik.", en: "The Bull is a prominent winter figure along the ecliptic." }, factSources, lastReviewedAt: reviewedAt },
  { id: "ursa-major", name: { de: "Großer Bär", en: "Ursa Major" }, recognitionHint: { de: "Sieben helle Sterne bilden den bekannten Großen Wagen.", en: "Seven bright stars form the familiar Big Dipper." }, shortDescription: { de: "Die große nördliche Figur enthält einen nützlichen Wegweiser zum Polarstern.", en: "This large northern figure contains a useful pointer toward Polaris." }, factSources, lastReviewedAt: reviewedAt },
  { id: "ursa-minor", name: { de: "Kleiner Bär", en: "Ursa Minor" }, recognitionHint: { de: "Der Polarstern sitzt am Ende der Deichsel des Kleinen Wagens.", en: "Polaris sits at the end of the Little Dipper's handle." }, shortDescription: { de: "Die kleine zirkumpolare Figur umschließt den nördlichen Himmelspol.", en: "This small circumpolar figure surrounds the north celestial pole." }, factSources, lastReviewedAt: reviewedAt },
] as const;

export const constellationCopyById = new Map(constellationCopy.map((entry) => [entry.id, entry]));

