import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { LegalPageShell } from "@/components/legal-page-shell";
import { isLocale, locales, type Locale } from "@/lib/i18n/config";
import { localizedLinks } from "@/lib/i18n/links";
import { legal, legalAddressLines } from "@/lib/legal/config";

export const dynamic = "force-static";
export const dynamicParams = false;
export function generateStaticParams() { return locales.map((locale) => ({ locale })); }

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  const de = locale === "de";
  return { title: de ? "Datenschutzerklärung" : "Privacy policy", description: de ? "Informationen zur Verarbeitung personenbezogener Daten bei Stargazing Index." : "Information about personal-data processing at Stargazing Index.", robots: { index: false, follow: true }, alternates: { canonical: localizedLinks.privacy(locale), languages: Object.fromEntries(locales.map((item) => [item, localizedLinks.privacy(item)])) } };
}

export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: localeParam } = await params;
  if (!isLocale(localeParam)) notFound();
  const locale = localeParam as Locale;
  const de = locale === "de";
  return (
    <LegalPageShell locale={locale} eyebrow={de ? "Rechtliches · Datenschutz" : "Legal · privacy"} title={de ? "Datenschutzerklärung" : "Privacy policy"} description={de ? "Diese Hinweise erklären transparent, welche Daten beim Besuch verarbeitet werden und welche Rechte du hast." : "This notice explains what data is processed when you visit and which rights you have."}>
      <section className="event-summary" aria-labelledby="privacy-controller-title"><h2 id="privacy-controller-title">{de ? "1. Verantwortlicher" : "1. Controller"}</h2><address>{legal.businessName}<br />{de ? "Inhaber" : "Owner"}: {legal.owner}<br />{legalAddressLines(locale).map((line) => <span key={line}>{line}<br /></span>)}E-Mail: <a className="text-link" href={`mailto:${legal.email}`}>{legal.email}</a></address></section>
      <section className="event-summary" aria-labelledby="privacy-hosting-title"><h2 id="privacy-hosting-title">{de ? "2. Hosting und technische Bereitstellung" : "2. Hosting and technical delivery"}</h2><p>{de ? "Die Website wird als statische Website über Cloudflare bereitgestellt. Beim Abruf können insbesondere IP-Adresse, Zeitpunkt, angeforderte URL, Referrer, Browser- und Systeminformationen sowie Daten zur technischen Übertragung verarbeitet werden. Die Verarbeitung dient der sicheren, stabilen und effizienten Auslieferung sowie der Abwehr missbräuchlicher Zugriffe." : "The site is delivered as a static website through Cloudflare. Requests may process the IP address, time, requested URL, referrer, browser and system information, and technical routing data. This processing supports secure, stable, efficient delivery and protection against abusive access."}</p><p>{de ? "Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in Betrieb, Sicherheit und Verfügbarkeit der Website. Cloudflare verarbeitet Kunden-Logs als Auftragsverarbeiter. Empfänger können Cloudflare Germany GmbH und Unternehmen der Cloudflare-Gruppe sein." : "The legal basis is Article 6(1)(f) GDPR; our legitimate interest is operating, securing, and keeping the site available. Cloudflare processes customer logs as a processor. Recipients may include Cloudflare Germany GmbH and Cloudflare group companies."}</p><p>{de ? "Bei Übermittlungen in die USA stützt Cloudflare sich nach eigener Angabe auf die Zertifizierung unter dem EU–US Data Privacy Framework und ersatzweise auf EU-Standardvertragsklauseln mit ergänzenden Schutzmaßnahmen. Technische Daten werden nur so lange gespeichert, wie dies für Betrieb, Sicherheit oder gesetzliche Pflichten erforderlich ist." : "For transfers to the United States, Cloudflare states that it relies on certification under the EU–US Data Privacy Framework and, if necessary, EU Standard Contractual Clauses with supplementary safeguards. Technical data is retained only as long as required for operations, security, or legal obligations."}</p><p><a className="text-link" href="https://www.cloudflare.com/privacypolicy/" rel="noreferrer">{de ? "Datenschutzrichtlinie von Cloudflare ↗" : "Cloudflare privacy policy ↗"}</a></p></section>
      <section className="event-summary" aria-labelledby="privacy-storage-title"><h2 id="privacy-storage-title">{de ? "3. Cookies und Browser-Speicher" : "3. Cookies and browser storage"}</h2><p>{de ? "Die Website setzt keine Analyse-, Marketing- oder Werbe-Cookies ein und speichert selbst keine Informationen in localStorage oder sessionStorage. Die interaktive Himmelsdarstellung hält ihren aktuellen Zustand nur vorübergehend im Arbeitsspeicher der geöffneten Seite." : "The site does not use analytics, marketing, or advertising cookies and does not itself store information in localStorage or sessionStorage. The interactive sky keeps its current state only temporarily in the memory of the open page."}</p></section>
      <section className="event-summary" aria-labelledby="privacy-email-title"><h2 id="privacy-email-title">{de ? "4. Kontakt per E-Mail" : "4. Email contact"}</h2><p>{de ? "Wenn du uns eine E-Mail sendest, verarbeiten wir Absenderadresse, Inhalt und weitere freiwillige Angaben zur Bearbeitung deiner Anfrage. Rechtsgrundlage ist je nach Inhalt Art. 6 Abs. 1 lit. b DSGVO für vorvertragliche Kommunikation oder Art. 6 Abs. 1 lit. f DSGVO für allgemeine Anfragen und redaktionelle Hinweise. Wir löschen die Daten, sobald sie für den Zweck nicht mehr erforderlich sind, sofern keine gesetzlichen Aufbewahrungspflichten bestehen." : "If you email us, we process the sender address, message, and any voluntary information to respond. Depending on the request, the legal basis is Article 6(1)(b) GDPR for pre-contractual communication or Article 6(1)(f) GDPR for general requests and editorial feedback. We delete the data when it is no longer required for that purpose unless statutory retention duties apply."}</p></section>
      <section className="event-summary" aria-labelledby="privacy-links-title"><h2 id="privacy-links-title">{de ? "5. Externe Links und Affiliate-Links" : "5. External and affiliate links"}</h2><p>{de ? "Beim Öffnen eines externen Links verlässt du diese Website; der jeweilige Anbieter verarbeitet Daten nach seiner eigenen Datenschutzerklärung. Gekennzeichnete Viator-Links können entweder zu einem einzeln geprüften Angebot oder zu einer Suche für die jeweilige Destination führen und enthalten unsere Affiliate-ID. Wenn du darüber buchst, können wir eine Provision erhalten, ohne dass dir zusätzliche Kosten entstehen. Auf dieser Website wird dafür kein Viator-Skript geladen und kein Viator-Cookie gesetzt. Erst nach dem Anklicken verarbeitet Viator den Aufruf nach seiner eigenen Datenschutzerklärung." : "When you open an external link, you leave this site and the destination processes data under its own privacy notice. Labelled Viator links may lead either to an individually reviewed offer or to a search for the relevant destination and include our affiliate ID. If you book through one of these links, we may earn a commission at no extra cost to you. No Viator script is loaded and no Viator cookie is set on this site. Viator processes the visit under its own privacy notice only after you click the link."}</p><p><a className="text-link" href="https://www.viator.com/support/privacyPolicy" rel="noreferrer">{de ? "Datenschutzerklärung von Viator ↗" : "Viator privacy policy ↗"}</a></p></section>
      <section className="event-summary" aria-labelledby="privacy-rights-title"><h2 id="privacy-rights-title">{de ? "6. Deine Rechte" : "6. Your rights"}</h2><p>{de ? "Du hast nach Maßgabe der DSGVO insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung kannst du jederzeit für die Zukunft widerrufen. Zur Ausübung genügt eine E-Mail an die oben genannte Adresse." : "Subject to the GDPR, you have rights including access, correction, erasure, restriction, portability, and objection. You may withdraw consent with future effect at any time. To exercise a right, email the address above."}</p><p>{de ? "Du hast außerdem das Recht, dich bei einer Datenschutzaufsichtsbehörde zu beschweren. Für den Verantwortlichen ist insbesondere die Berliner Beauftragte für Datenschutz und Informationsfreiheit zuständig." : "You also have the right to complain to a data-protection supervisory authority. The Berlin Commissioner for Data Protection and Freedom of Information is the primary authority for the controller."}</p><p><a className="text-link" href="https://www.datenschutz-berlin.de/buergerinnen-und-buerger/beschwerde/" rel="noreferrer">{de ? "Beschwerdeinformationen der Berliner Aufsicht ↗" : "Berlin authority complaint information ↗"}</a></p></section>
      <footer className="event-footer"><p>{de ? "Stand und letzte rechtliche Prüfung" : "Effective date and last legal review"}: {legal.lastLegalReview}</p></footer>
    </LegalPageShell>
  );
}
